### ISSUE TITLE
[BUG]商店页面恢复理智会导致卡住

### ISSUE THREAD

**Issue by sstareven** [KIYI671/AhabAssistantLimbusCompany#10]
如题，如果所有人物都是满理智，那么两个恢复理智的选项就会变成灰色，估计此时没有可识别物，导致光标只会按Skip按钮，不会离开商店。需要加入条件退出该界面。

**Comment by KIYI671** [comment]
> 如题，如果所有人物都是满理智，那么两个恢复理智的选项就会变成灰色，估计此时没有可识别物，导致光标只会按Skip按钮，不会离开商店。需要加入条件退出该界面。

之前有人反馈过这个问题，在V0.0.2（现在这个版本）已经解决了，它会最多尝试五次点击跳过，这是为了防止电脑配置不足导致的卡顿现象，如果在五次跳过后仍旧在治疗选择页面，它会自动退出。

**Comment by sstareven** [comment]
![H(XA0L~8L{)CU JY{OMIFS0](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/45038473/3d7f651f-659b-40ea-a1f3-2bc2c495b509)
![image](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/45038473/2f03fcd2-9eec-48f9-bcbf-0029b8bcbaa8)
确认了自己用的就是最新版本的，的确还是会卡住，具体显示的log是长这样的，推测可能是过早离开了“镜牢休息房间”

**Comment by KIYI671** [comment]
> ![H(XA0L~8L{)CU JY{OMIFS0](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/45038473/3d7f651f-659b-40ea-a1f3-2bc2c495b509)
> ![image](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/45038473/2f03fcd2-9eec-48f9-bcbf-0029b8bcbaa8)
> 确认了自己用的就是最新版本的，的确还是会卡住，具体显示的log是长这样的，推测可能是过早离开了“镜牢休息房间”

脚本界面中的log是极其简略版本的，只是为了实时观测脚本运行情况，并不能看出多少信息，请前往脚本文件夹下的log文件夹，寻找并上传出现这个问题当日的，后缀为debug的log文件

**Comment by sstareven** [comment]
[2024-06-29.0001.debugLog.log](https://github.com/user-attachments/files/16053761/2024-06-29.0001.debugLog.log)
Debug Log在这里

**Comment by KIYI671** [comment]
> [2024-06-29.0001.debugLog.log](https://github.com/user-attachments/files/16053761/2024-06-29.0001.debugLog.log) Debug Log在这里

我看你之前的截图，似乎是在6月27日晚上23点出现了此问题，你这次上传的是6月29日的日志，而且日志记录的内容全程处于死循环状态，无法了解问题发生的有效信息

**Comment by sstareven** [comment]
因为这个是可复刻BUG，实际情况截图和LOG一致，所以我觉得截图和log之间不冲突；所以基本挂着放1~2个循环不到就会卡住，一般在第四层最后的商店会卡住。

**Comment by sstareven** [comment]
![image](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/45038473/edaa1771-bcd2-4208-8ea2-db5346731814)
具体的屏幕参数如上，不清楚这个有没有关系

**Comment by KIYI671** [comment]
> ![image](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/45038473/edaa1771-bcd2-4208-8ea2-db5346731814)
> 具体的屏幕参数如上，不清楚这个有没有关系

很可能与屏幕比例有关，我所使用的屏幕比例是100%，运行到现在数百次，没有遇到过这种情况。
不过也可能无关，因为我在写这部分程序逻辑时，使用的是ocr，正常应该不会被影响。

我需要当时的日志是因为需要了解进入这个死循环的原因，如果提供的日志不包含这部分的话，无法了解为何会产生这个问题。

**Comment by KIYI671** [comment]
> 如题，如果所有人物都是满理智，那么两个恢复理智的选项就会变成灰色，估计此时没有可识别物，导致光标只会按Skip按钮，不会离开商店。需要加入条件退出该界面。

终于遇到了一次这个问题，是升级EGO饰品时出现的问题，现在已经解决了，可以前往release更新
