### ISSUE TITLE
AALC broke after update

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#11]
After update it seems to not recognize the full_team.png file or something and it keeps choosing charaters on a loop
I tried to change full_team.png to a screenshot of newer 6/6 picture, but it did the same thing, so I don't know how to fix it 

https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/104787079/0c8b25d3-12e3-4fc7-9e1b-a0a7a3b62eed

[2024-07-04.0001.debugLog.log](https://github.com/user-attachments/files/16093697/2024-07-04.0001.debugLog.log)

**Comment by KIYI671** [comment]
> After update it seems to not recognize the full_team.png file or something and it keeps choosing charaters on a loop I tried to change full_team.png to a screenshot of newer 6/6 picture, but it did the same thing, so I don't know how to fix it
> 
>  Limbus.Company.2024.07.04.-.07.59.41.02.mp4 
> [2024-07-04.0001.debugLog.log](https://github.com/user-attachments/files/16093697/2024-07-04.0001.debugLog.log)

Hello, regarding this issue, I found that the Moon Project Company modified the font at position 6/6. There are two solutions now. One may slightly increase the recognition time of the team interface, but it is more stable and will not be affected if the font is changed again in the future. The other solution is to replace the screenshot here, but you need to change the screenshot again when you change the font in the future. Which solution do you prefer?

TIP: If you change the recognition image yourself, you need to capture the image at a resolution of 2560*1440 for replacement to be effective (originally prepared to be a product for multi-resolution adaptation)

**Comment by arraf270** [comment]
> > After update it seems to not recognize the full_team.png file or something and it keeps choosing charaters on a loop I tried to change full_team.png to a screenshot of newer 6/6 picture, but it did the same thing, so I don't know how to fix it
> > 
> >  Limbus.Company.2024.07.04.-.07.59.41.02.mp4 
> > [2024-07-04.0001.debugLog.log](https://github.com/user-attachments/files/16093697/2024-07-04.0001.debugLog.log)
> 
> Hello, regarding this issue, I found that the Moon Project Company modified the font at position 6/6. There are two solutions now. One may slightly increase the recognition time of the team interface, but it is more stable and will not be affected if the font is changed again in the future. The other solution is to replace the screenshot here, but you need to change the screenshot again when you change the font in the future. Which solution do you prefer?
> 
> TIP: If you change the recognition image yourself, you need to capture the image at a resolution of 2560*1440 for replacement to be effective (originally prepared to be a product for multi-resolution adaptation)

I think the more stable solution is good

**Comment by KIYI671** [comment]
> > > After update it seems to not recognize the full_team.png file or something and it keeps choosing charaters on a loop I tried to change full_team.png to a screenshot of newer 6/6 picture, but it did the same thing, so I don't know how to fix it
> > > Limbus.Company.2024.07.04.-.07.59.41.02.mp4
> > > [2024-07-04.0001.debugLog.log](https://github.com/user-attachments/files/16093697/2024-07-04.0001.debugLog.log)
> > 
> > 
> > Hello, regarding this issue, I found that the Moon Project Company modified the font at position 6/6. There are two solutions now. One may slightly increase the recognition time of the team interface, but it is more stable and will not be affected if the font is changed again in the future. The other solution is to replace the screenshot here, but you need to change the screenshot again when you change the font in the future. Which solution do you prefer?
> > TIP: If you change the recognition image yourself, you need to capture the image at a resolution of 2560*1440 for replacement to be effective (originally prepared to be a product for multi-resolution adaptation)
> 
> I think the more stable solution is good

Hello, the problem found this time has been solved. You can go to release to download the update, and this update also fixes the problem of entering the event at the moment of death that you reported before.

The emergence of this problem made me realize how fragile my script program is. When encountering this problem of changing the text spacing, it can't be used normally immediately. I hope that the Moon Project Company will not do this again in the future. T_T

**Comment by KIYI671** [comment]
I regret to tell you that I found that in the 20240704 update, in order to solve the problem of "the death of the sinner and the entry event at the beginning of the round, causing an error", it actually caused more errors. Because this is a very rare event, I rolled back this function to the previous version. Please go to release to download the new version to replace it.

**Comment by KIYI671** [comment]
> I regret to tell you that I found that in the 20240704 update, in order to solve the problem of "the death of the sinner and the entry event at the beginning of the round, causing an error", it actually caused more errors. Because this is a very rare event, I rolled back this function to the previous version. Please go to release to download the new version to replace it.

It was found that the battle interruption problem was not related to this repair, so the battle logic was re-completed and the rollback was canceled.
