### ISSUE TITLE
The Noon of Violet floor theme pack softlocks the program

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#13]
The new floor pack can't be beaten because its boss battle is Chain Battle, which AALC can't recognize and it softlocks, selecting and de-selecting characters over and over again. 

Adding the pack to keyword blacklist doesn't help, it still chooses it all the time

**Comment by KIYI671** [comment]
> The new floor pack can't be beaten because its boss battle is Chain Battle, which AALC can't recognize and it softlocks, selecting and de-selecting characters over and over again.
> 
> Adding the pack to keyword blacklist doesn't help, it still chooses it all the time

What keywords did you add? I added "violet" and never entered the theme pack again.

**Comment by arraf270** [comment]
> > The new floor pack can't be beaten because its boss battle is Chain Battle, which AALC can't recognize and it softlocks, selecting and de-selecting characters over and over again.
> > 
> > Adding the pack to keyword blacklist doesn't help, it still chooses it all the time
> 
> What keywords did you add? I added "violet" and never entered the theme pack again.

Let me try that, I realized that I added the whole "The Noon of Violet" name instead of just "violet", I might be stupid lol

**Comment by arraf270** [comment]
I added just "violet" and "noon" and everything is working fine again, thank you
