### ISSUE TITLE
AALC doesn't recognize Select Event Effect screen

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#17]
I think the program doesn't know what to do with this screen/gets stuck on it

![Limbus Company Screenshot 2024 12 01 - 05 11 36 87](https://github.com/user-attachments/assets/4057cb43-ee00-41f7-bc8f-6d3fc87598c6)

**Comment by KIYI671** [comment]
I have not encountered this situation in the previous test. Please choose it yourself and wait for subsequent updates.

**Comment by KIYI671** [comment]
> I think the program doesn't know what to do with this screen/gets stuck on it
> 
> ![Limbus Company Screenshot 2024 12 01 - 05 11 36 87](https://private-user-images.githubusercontent.com/104787079/391301416-4057cb43-ee00-41f7-bc8f-6d3fc87598c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMjAzMTEsIm5iZiI6MTczMzAyMDAxMSwicGF0aCI6Ii8xMDQ3ODcwNzkvMzkxMzAxNDE2LTQwNTdjYjQzLWVlMDAtNDFmNy1iYzhmLTZkM2ZjODc1OThjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQwMjI2NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzczNTc3YzgzNWYxY2FkNDY5ZGNlMmVmZDQyODFhOTRjYWY0N2U3MzQzOTY3OWI1N2M4YzA4ODY4ODNlNzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TinxDpmiZQzhPOtXsVLN_wtDd29028pn8wOUVJVPEhg)

I have tried to add the logic for this event, but since the identification image used is the one you uploaded this time, I can only test it in my mind, and it should be fine.
Please go to release to download the latest update.

**Comment by arraf270** [comment]
I still have this event opened in Limbus, I will test it right now

**Comment by arraf270** [comment]
It works now, thank you a lot!!!
