### ISSUE TITLE
AALC stuck on Theme Pack choice

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#20]
The program gets stuck randomly on a theme pack selection screen (usually 4-5 floor) and there is a weird error in the logs, how can I fix it? 

[2024-12-02.0001.debugLog.log](https://github.com/user-attachments/files/17973115/2024-12-02.0001.debugLog.log)
[2024-12-02.0001.infoLog.log](https://github.com/user-attachments/files/17973140/2024-12-02.0001.infoLog.log)
![image](https://github.com/user-attachments/assets/10172925-7ceb-46c5-a27d-655c59b7cd97)

**Comment by KIYI671** [comment]
> The program gets stuck randomly on a theme pack selection screen (usually 4-5 floor) and there is a weird error in the logs, how can I fix it? 
> 
> [2024-12-02.0001.debugLog.log](https://github.com/user-attachments/files/17973115/2024-12-02.0001.debugLog.log)
> [2024-12-02.0001.infoLog.log](https://github.com/user-attachments/files/17973140/2024-12-02.0001.infoLog.log)
> ![image](https://github.com/user-attachments/assets/10172925-7ceb-46c5-a27d-655c59b7cd97)
> 

The update that adapted MD5 added a blacklist of many theme packs, and the picture shows a situation where all three theme packs (including after the refresh) are in the blacklist (the bosses targeted from left to right are Time Murderer, Golden Hasa, and Human Skin Prophecy Book). Since I personally have been using the 60 starlight bonus, I didn't realize that there were only three options available for the theme packs with the other low level starlight bonuses. The solution is:Modify the yaml file of blacklist under the folder to remove part of the blacklist; or change the team more often and use the high starlight addon (there are 5 optional theme packs for the high starlight addon, plus 10 for the refresh, and it is rare to come across this situation).

**Comment by arraf270** [comment]
I see, I think it would also be good to make AALC always choose "Interstellar Travel" bonus, as it is always avaliable with 30 rest bonus and gives +1 Theme Pack choice (changing the team often is hard because I usually farm mirror dungeons in large quantities). 
I will remove a part of blacklist for now, thanks for the advice
Randomly selecting a theme pack in case of all packs being blacklisted is a good idea, looking forward to it :)

![image](https://github.com/user-attachments/assets/b336b427-fb40-473d-b240-c399966fcbf0)

**Comment by KIYI671** [comment]
> I see, I think it would also be good to make AALC always choose "Interstellar Travel" bonus, as it is always avaliable with 30 rest bonus and gives +1 Theme Pack choice (changing the team often is hard because I usually farm mirror dungeons in large quantities). 
> I will remove a part of blacklist for now, thanks for the advice
> Randomly selecting a theme pack in case of all packs being blacklisted is a good idea, looking forward to it :)
> 
> ![image](https://github.com/user-attachments/assets/b336b427-fb40-473d-b240-c399966fcbf0)
> 

I understand what you mean through the translation software, but the difficulty of changing teams in your first paragraph is a translation problem, I can't understand it. the function of AALC is able to change teams automatically, you just need to set up the teams in advance in the "Sinner" page, and then in the dungeon team configuration page of the AALC mirror, you can set up the teams automatically.It is possible to choose which team to use.The orange boxes are shown below.

![Screenshot_2024-12-02-14-48-24-185_com.github.android-edit.jpg](https://github.com/user-attachments/assets/3cd465cc-1216-4630-8e02-d801ef481016)

**Comment by arraf270** [comment]
> > I see, I think it would also be good to make AALC always choose "Interstellar Travel" bonus, as it is always avaliable with 30 rest bonus and gives +1 Theme Pack choice (changing the team often is hard because I usually farm mirror dungeons in large quantities). 
> > I will remove a part of blacklist for now, thanks for the advice
> > Randomly selecting a theme pack in case of all packs being blacklisted is a good idea, looking forward to it :)
> > 
> > ![image](https://github.com/user-attachments/assets/b336b427-fb40-473d-b240-c399966fcbf0)
> > 
> 
> I understand what you mean through the translation software, but the difficulty of changing teams in your first paragraph is a translation problem, I can't understand it. the function of AALC is able to change teams automatically, you just need to set up the teams in advance in the "Sinner" page, and then in the dungeon team configuration page of the AALC mirror, you can set up the teams automatically.It is possible to choose which team to use.The orange boxes are shown below.
> 
> ![Screenshot_2024-12-02-14-48-24-185_com.github.android-edit.jpg](https://github.com/user-attachments/assets/3cd465cc-1216-4630-8e02-d801ef481016)
> 
> 

Oh, you are right, I've been using one burn team for so long I forgot this function existed 😅
