### ISSUE TITLE
希望向README中添加从源码构建的步骤

### ISSUE THREAD

**Issue by NaNExist** [KIYI671/AhabAssistantLimbusCompany#30]
希望向README中添加从源码构建的步骤，这样就能方便更多的人加入项目开发中来（

**Comment by KIYI671** [comment]
> 希望向README中添加从源码构建的步骤，这样就能方便更多的人加入项目开发中来（

请问有没有什么相关的案例或者比较基础的教程？我没有系统学过这方面的内容，对项目流程也完全没有了解，没有这方面的经验。
如果是指打包项目为exe，我都是使用 pyinstaller main.spec 这段代码直接操作，之后把其他两个文件夹和两个yaml文件手动复制进去的。

**Comment by NaNExist** [comment]
其实我也没有系统学过(
我觉得一个就是在README里面写明每一步构建的过程，以及需要的依赖（比如需要的pyinstaller的版本），然后最后支持的平台。虽然limbus只有win版本，但是win也有不同架构来着(
然后就是实现CI/CD（可持续化集成/部署），这样就能每次新版本自动打包发布在GitHub上，pr时候也能初步验证代码有没有冲突之类的问题↖(^ω^)↗

**Comment by KIYI671** [comment]
> 其实我也没有系统学过(
> 我觉得一个就是在README里面写明每一步构建的过程，以及需要的依赖（比如需要的pyinstaller的版本），然后最后支持的平台。虽然limbus只有win版本，但是win也有不同架构来着(
> 然后就是实现CI/CD（可持续化集成/部署），这样就能每次新版本自动打包发布在GitHub上，pr时候也能初步验证代码有没有冲突之类的问题↖(^ω^)↗

看起来有点复杂，CI/CD我都没听说过( ﾟ∀。)
我慢慢来吧，补一补基础，边学顺便边试着完成上述操作

**Comment by NaNExist** [comment]
我晚上看看能不能搓一个CD出来⊹꙳ ˶˙ᵕ˙˶ ⊹꙳

**Comment by NaNExist** [comment]
现在需要python库的依赖和版本，我猜谜猜一下午也没构建出一个能用的版本。nb_log的bug换用高版本还是有问题

**Comment by KIYI671** [comment]
> 现在需要python库的依赖和版本，我猜谜猜一下午也没构建出一个能用的版本。nb_log的bug换用高版本还是有问题

今晚有事不太方便，明天晚上才能回家接触到电脑，得等明晚才能看看你提交的代码，并导出requirement.txt。
说实话我基本没怎么用过github，这是我第一个项目，提交、合并、审阅之类的操作，我得摸索一下( ﾟ∀。)
说实话nb_log为啥会出这个问题我没搞懂，为啥能解决也没搞懂，是典型的能跑就行的弗兰肯斯坦

**Comment by NaNExist** [comment]
> > 现在需要python库的依赖和版本，我猜谜猜一下午也没构建出一个能用的版本。nb_log的bug换用高版本还是有问题
> 
> 今晚有事不太方便，明天晚上才能回家接触到电脑，得等明晚才能看看你提交的代码，并导出requirement.txt。 说实话我基本没怎么用过github，这是我第一个项目，提交、合并、审阅之类的操作，我得摸索一下( ﾟ∀。) 说实话nb_log为啥会出这个问题我没搞懂，为啥能解决也没搞懂，是典型的能跑就行的弗兰肯斯坦

没事没事不急的。我仅有的一点经验还是上一个小助手（已烂尾）项目学到的一点经验

**Comment by maosasagawa** [comment]
构建起来不复杂啊我自己改了点一直在用
# requirements.txt

attrs==24.2.0
certifi==2024.8.30
cffi==1.17.1
chained_mode_time_tool==0.4
charset-normalizer==3.4.0
concurrent-log-handler==0.9.23
cryptography==44.0.0
darkdetect==0.8.0
Deprecated==1.2.14
idna==3.10
logging_tree==1.10
MouseInfo==0.1.3
nb-libs==1.8
nb-log==13.2
nb_filelock==0.9
numpy==2.1.3
opencv-python==4.10.0.84
pillow==11.0.0
portalocker==2.3.2
pyasn1==0.6.1
pyasn1_modules==0.4.1
PyAutoGUI==0.9.54
pycparser==2.22
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pynput==1.7.7
pyperclip==1.9.0
PyQt-Fluent-Widgets==1.7.2
PyQt5==5.15.11
PyQt5-Frameless-Window==0.4.3
PyQt5-Qt5==5.15.2
PyQt5_sip==12.16.0
PyRect==0.2.0
PyScreeze==1.0.1
python-json-logger==0.1.10
pytweening==1.2.0
pytz==2024.2
pywin32==308
requests==2.32.3
ruamel.yaml==0.17.40
ruamel.yaml.clib==0.2.12
service-identity==24.2.0
six==1.17.0
tomorrow3==1.1.0
tzdata==2024.2
tzlocal==5.2
urllib3==2.2.3
wrapt==1.17.0

**Comment by KIYI671** [comment]
> > 我之前自己改了点一直在用，这是我用的构建希望可以给你带来帮助。原本是打算测试下能不能自动适配各种分辨率的，但改了一点之后也遇到了nb_log的问题，换了其他的log之后也是一样的，但是原本的代码是能正常构建正常使用的，所以我就放弃修改了（
> > 
> > # requirements.txt(3.12.8)
> > attrs==24.2.0 certifi==2024.8.30 cffi==1.17.1 chained_mode_time_tool==0.4 charset-normalizer==3.4.0 concurrent-log-handler==0.9.23 cryptography==44.0.0 darkdetect==0.8.0 Deprecated==1.2.14 idna==3.10 logging_tree==1.10 MouseInfo==0.1.3 nb-libs==1.8 nb-log==13.2 nb_filelock==0.9 numpy==2.1.3 opencv-python==4.10.0.84 pillow==11.0.0 portalocker==2.3.2 pyasn1==0.6.1 pyasn1_modules==0.4.1 PyAutoGUI==0.9.54 pycparser==2.22 PyGetWindow==0.0.9 PyMsgBox==1.0.9 pynput==1.7.7 pyperclip==1.9.0 PyQt-Fluent-Widgets==1.7.2 PyQt5==5.15.11 PyQt5-Frameless-Window==0.4.3 PyQt5-Qt5==5.15.2 PyQt5_sip==12.16.0 PyRect==0.2.0 PyScreeze==1.0.1 python-json-logger==0.1.10 pytweening==1.2.0 pytz==2024.2 pywin32==308 requests==2.32.3 ruamel.yaml==0.17.40 ruamel.yaml.clib==0.2.12 service-identity==24.2.0 six==1.17.0 tomorrow3==1.1.0 tzdata==2024.2 tzlocal==5.2 urllib3==2.2.3 wrapt==1.17.0
> 
> 感谢，但是这个依赖还是不能正常跑起来（

辛苦了，等我明晚把依赖表导出来试试
不过导出来也不知道能不能成。我之前打包试了好几种方法，有的也要导出依赖表，但是最后都打包失败了，只有现在使用pyinstaller main.spec的方式能成功

**Comment by KIYI671** [comment]
绝了，我用 pipreqs --ignore .venv --force 导出的 requirements.txt只有这么几行，还有重复的，能用吗？
用诸如“pipreqs ./ --encoding=utf-8 --force ”之类的，都报编码错误，只有上面那行代码能用
nb_log==12.7
PyAutoGUI==0.9.54
pynput==1.7.7
PyQt_Fluent_Widgets==1.4.6
python_json_logger==0.1.10
pywin32==306
pywin32==308
ruamel.base==1.0.0

**Comment by NaNExist** [comment]
> 绝了，我用 pipreqs --ignore .venv --force 导出的 requirements.txt只有这么几行，还有重复的，能用吗？ 用诸如“pipreqs ./ --encoding=utf-8 --force ”之类的，都报编码错误，只有上面那行代码能用 nb_log==12.7 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt_Fluent_Widgets==1.4.6 python_json_logger==0.1.10 pywin32==306 pywin32==308 ruamel.base==1.0.0
> 
> INFO: Not scanning for jupyter notebooks. WARNING: Import named "load_config_py2" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "load_config_py2" does not exist or network problems WARNING: Import named "ruamel.base" not found locally. Trying to resolve it at the PyPI server. WARNING: Import named "ruamel.base" was resolved to "ruamel.base:1.0.0" package (https://pypi.org/project/ruamel.base/). Please, verify manually the final list of requirements.txt to avoid possible dependency confusions. WARNING: Import named "win32con" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "win32con" does not exist or network problems INFO: Successfully saved requirements file in F:\AhabAssistantLimbusCompany\AhabAssistantLimbusCompany\requirements.txt 中途报出的信息，感觉怪怪的，我没有安装ruamel.base这个库，用的ruamel.yaml
> 
> 以下是使用pycharm导出的，但是又少了nb_log和PyQt_Fluent_Widgets numpy==1.26.3 opencv-python==4.9.0.80 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt5==5.15.10 pywin32==308

还是不行，神了
这个项目为什么能构建已经要变成未解之谜了

**Comment by KIYI671** [comment]
> > 绝了，我用 pipreqs --ignore .venv --force 导出的 requirements.txt只有这么几行，还有重复的，能用吗？ 用诸如“pipreqs ./ --encoding=utf-8 --force ”之类的，都报编码错误，只有上面那行代码能用 nb_log==12.7 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt_Fluent_Widgets==1.4.6 python_json_logger==0.1.10 pywin32==306 pywin32==308 ruamel.base==1.0.0
> > INFO: Not scanning for jupyter notebooks. WARNING: Import named "load_config_py2" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "load_config_py2" does not exist or network problems WARNING: Import named "ruamel.base" not found locally. Trying to resolve it at the PyPI server. WARNING: Import named "ruamel.base" was resolved to "ruamel.base:1.0.0" package (https://pypi.org/project/ruamel.base/). Please, verify manually the final list of requirements.txt to avoid possible dependency confusions. WARNING: Import named "win32con" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "win32con" does not exist or network problems INFO: Successfully saved requirements file in F:\AhabAssistantLimbusCompany\AhabAssistantLimbusCompany\requirements.txt 中途报出的信息，感觉怪怪的，我没有安装ruamel.base这个库，用的ruamel.yaml
> > 以下是使用pycharm导出的，但是又少了nb_log和PyQt_Fluent_Widgets numpy==1.26.3 opencv-python==4.9.0.80 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt5==5.15.10 pywin32==308
> 
> 还是不行，神了 这个项目为什么能构建已经要变成未解之谜了

看起来得试一下重新下载代码下来，重新安装依赖到可以运行，再导出试试了

**Comment by NaNExist** [comment]
> > > 绝了，我用 pipreqs --ignore .venv --force 导出的 requirements.txt只有这么几行，还有重复的，能用吗？ 用诸如“pipreqs ./ --encoding=utf-8 --force ”之类的，都报编码错误，只有上面那行代码能用 nb_log==12.7 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt_Fluent_Widgets==1.4.6 python_json_logger==0.1.10 pywin32==306 pywin32==308 ruamel.base==1.0.0
> > > INFO: Not scanning for jupyter notebooks. WARNING: Import named "load_config_py2" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "load_config_py2" does not exist or network problems WARNING: Import named "ruamel.base" not found locally. Trying to resolve it at the PyPI server. WARNING: Import named "ruamel.base" was resolved to "ruamel.base:1.0.0" package (https://pypi.org/project/ruamel.base/). Please, verify manually the final list of requirements.txt to avoid possible dependency confusions. WARNING: Import named "win32con" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "win32con" does not exist or network problems INFO: Successfully saved requirements file in F:\AhabAssistantLimbusCompany\AhabAssistantLimbusCompany\requirements.txt 中途报出的信息，感觉怪怪的，我没有安装ruamel.base这个库，用的ruamel.yaml
> > > 以下是使用pycharm导出的，但是又少了nb_log和PyQt_Fluent_Widgets numpy==1.26.3 opencv-python==4.9.0.80 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt5==5.15.10 pywin32==308
> > 
> > 
> > 还是不行，神了 这个项目为什么能构建已经要变成未解之谜了
> 
> 看起来得试一下重新下载代码下来，重新安装依赖到可以运行，再导出试试了

现在问题还是会抛出"AttributeError: 'NoneType' object has no attribute 'write'"的错误
顺便问下python的版本是3.12.什么

**Comment by KIYI671** [comment]
> > > > 绝了，我用 pipreqs --ignore .venv --force 导出的 requirements.txt只有这么几行，还有重复的，能用吗？ 用诸如“pipreqs ./ --encoding=utf-8 --force ”之类的，都报编码错误，只有上面那行代码能用 nb_log==12.7 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt_Fluent_Widgets==1.4.6 python_json_logger==0.1.10 pywin32==306 pywin32==308 ruamel.base==1.0.0
> > > > INFO: Not scanning for jupyter notebooks. WARNING: Import named "load_config_py2" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "load_config_py2" does not exist or network problems WARNING: Import named "ruamel.base" not found locally. Trying to resolve it at the PyPI server. WARNING: Import named "ruamel.base" was resolved to "ruamel.base:1.0.0" package (https://pypi.org/project/ruamel.base/). Please, verify manually the final list of requirements.txt to avoid possible dependency confusions. WARNING: Import named "win32con" not found locally. Trying to resolve it at the PyPI server. WARNING: Package "win32con" does not exist or network problems INFO: Successfully saved requirements file in F:\AhabAssistantLimbusCompany\AhabAssistantLimbusCompany\requirements.txt 中途报出的信息，感觉怪怪的，我没有安装ruamel.base这个库，用的ruamel.yaml
> > > > 以下是使用pycharm导出的，但是又少了nb_log和PyQt_Fluent_Widgets numpy==1.26.3 opencv-python==4.9.0.80 PyAutoGUI==0.9.54 pynput==1.7.7 PyQt5==5.15.10 pywin32==308
> > > 
> > > 
> > > 还是不行，神了 这个项目为什么能构建已经要变成未解之谜了
> > 
> > 
> > 看起来得试一下重新下载代码下来，重新安装依赖到可以运行，再导出试试了
> 
> 现在问题还是会抛出"AttributeError: 'NoneType' object has no attribute 'write'"的错误 顺便问下python的版本是3.12.什么

 Python 3.12.1 (tags/v3.12.1:2305ca5, Dec  7 2023, 22:03:25) [MSC v.1937 64 bit (AMD64)] on win32

**Comment by NaNExist** [comment]
能不能看看pyinstaller构建时候的log QAQ
CD打包出来的也不能跑

**Comment by KIYI671** [comment]
attrs==24.2.0
certifi==2024.8.30
cffi==1.17.1
chained_mode_time_tool==0.4
charset-normalizer==3.4.0
concurrent-log-handler==0.9.23
cryptography==44.0.0
darkdetect==0.8.0
Deprecated==1.2.14
idna==3.10
logging_tree==1.10
MouseInfo==0.1.3
nb-libs==1.8
nb-log==13.2
nb_filelock==0.9
numpy==2.2.0
opencv-python==4.10.0.84
pillow==11.0.0
portalocker==2.3.2
pyasn1==0.6.1
pyasn1_modules==0.4.1
PyAutoGUI==0.9.54
pycparser==2.22
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pynput==1.7.7
pyperclip==1.9.0
PyQt-Fluent-Widgets==1.7.3
PyQt5==5.15.11
PyQt5-Frameless-Window==0.4.3
PyQt5-Qt5==5.15.2
PyQt5_sip==12.16.0
PyRect==0.2.0
PyScreeze==1.0.1
python-json-logger==0.1.10
pytweening==1.2.0
pytz==2024.2
pywin32==308
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.12
service-identity==24.2.0
six==1.17.0
tomorrow3==1.1.0
tzdata==2024.2
tzlocal==5.2
urllib3==2.2.3
wrapt==1.17.0


这波应该没问题，我重新下载项目，然后作为新项目重新安装各种依赖，直到可以正常运行

**Comment by KIYI671** [comment]
altgraph==0.17.4
attrs==24.2.0
certifi==2024.8.30
cffi==1.17.1
chained_mode_time_tool==0.4
charset-normalizer==3.4.0
concurrent-log-handler==0.9.23
cryptography==44.0.0
darkdetect==0.8.0
Deprecated==1.2.14
idna==3.10
logging_tree==1.10
MouseInfo==0.1.3
nb-libs==1.8
nb-log==13.2
nb_filelock==0.9
numpy==2.2.0
opencv-python==4.10.0.84
packaging==24.2
pefile==2023.2.7
pillow==11.0.0
portalocker==2.3.2
pyasn1==0.6.1
pyasn1_modules==0.4.1
PyAutoGUI==0.9.54
pycparser==2.22
PyGetWindow==0.0.9
pyinstaller==6.11.1
pyinstaller-hooks-contrib==2024.10
PyMsgBox==1.0.9
pynput==1.7.7
pyperclip==1.9.0
PyQt-Fluent-Widgets==1.7.3
PyQt5==5.15.11
PyQt5-Frameless-Window==0.4.3
PyQt5-Qt5==5.15.2
PyQt5_sip==12.16.0
PyRect==0.2.0
PyScreeze==1.0.1
python-json-logger==0.1.10
pytweening==1.2.0
pytz==2024.2
pywin32==308
pywin32-ctypes==0.2.3
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.12
service-identity==24.2.0
setuptools==75.6.0
six==1.17.0
tomorrow3==1.1.0
tzdata==2024.2
tzlocal==5.2
urllib3==2.2.3
wrapt==1.17.0

安装pyinstaller之后的requirements.txt

**Comment by KIYI671** [comment]
[pyinstaller_log.txt](https://github.com/user-attachments/files/18079851/pyinstaller_log.txt)
这个是使用pyinstaller构建时候的log

下面是pip freeze的导出的依赖
altgraph==0.17.4
asttokens==2.4.1
attrs==23.2.0
backcall==0.2.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.2.2
cffi==1.16.0
chained_mode_time_tool==0.4
charset-normalizer==3.3.2
colorama==0.4.6
concurrent-log-handler==0.9.23
contourpy==1.2.0
cryptography==42.0.7
cx_Logging==3.2.0
cycler==0.12.1
darkdetect==0.8.0
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
docopt==0.6.2
executing==2.0.1
fastjsonschema==2.19.1
fonttools==4.48.1
idna==3.7
ipython==8.12.3
jedi==0.19.1
Jinja2==3.1.4
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyterlab_pygments==0.3.0
kiwisolver==1.4.5
kuai_log==0.8
lief==0.14.1
markdown2==2.4.13
MarkupSafe==2.1.5
matplotlib==3.8.2
matplotlib-inline==0.1.7
mistune==3.0.2
MouseInfo==0.1.3
nb-log==12.7
nb_filelock==0.7
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
numpy==2.2.0
opencv-contrib-python==4.9.0.80
opencv-python==4.10.0.84
packaging==23.2
pandocfilters==1.5.1
parso==0.8.4
pefile==2023.2.7
pickleshare==0.7.5
pillow==10.2.0
Pillow-PIL==0.1.dev0
pipreqs==0.5.0
pipreqsnb==0.2.4
platformdirs==4.2.1
portalocker==2.8.2
prompt-toolkit==3.0.43
psutil==5.9.8
pure-eval==0.2.2
pyasn1==0.6.0
pyasn1_modules==0.4.0
PyAutoGUI==0.9.54
pycparser==2.22
PyGetWindow==0.0.9
Pygments==2.18.0
pyinstaller==6.5.0
pyinstaller-hooks-contrib==2024.3
PyMsgBox==1.0.9
pynput==1.7.7
pyparsing==3.1.1
pyperclip==1.8.2
PyQt-Fluent-Widgets==1.4.6
PyQt5==5.15.10
PyQt5-Frameless-Window==0.3.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
PyRect==0.2.0
PyScreeze==0.1.30
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
python-dateutil==2.8.2
python-json-logger==0.1.10
pytweening==1.0.7
pytz==2024.1
pywin32==308
pywin32-ctypes==0.2.2
PyYAML==6.0.1
pyzmq==26.0.3
referencing==0.35.1
requests==2.31.0
rpds-py==0.18.1
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
service-identity==24.1.0
setuptools==69.2.0
shiboken6==6.6.1
six==1.16.0
soupsieve==2.5
stack-data==0.6.3
svgwrite==1.4.3
tinycss2==1.3.0
tomorrow3==1.1.0
tornado==6.4
traitlets==5.14.3
tzdata==2024.1
tzlocal==5.2
urllib3==2.2.1
wcwidth==0.2.13
webencodings==0.5.1
wheel==0.43.0
wrapt==1.16.0
yarg==0.1.9

**Comment by KIYI671** [comment]
[pyinstaller_log.txt](https://github.com/user-attachments/files/18079892/pyinstaller_log.txt)
刚刚第一份使用pyinstaller构建时候的log大概率有问题，还是看这份吧

**Comment by NaNExist** [comment]
> [pyinstaller_log.txt](https://github.com/user-attachments/files/18079851/pyinstaller_log.txt)
> 这个是使用pyinstaller构建时候的log
> 
> 下面是pip freeze的导出的依赖
> altgraph==0.17.4
> asttokens==2.4.1
> attrs==23.2.0
> backcall==0.2.0
> beautifulsoup4==4.12.3
> bleach==6.1.0
> certifi==2024.2.2
> cffi==1.16.0
> chained_mode_time_tool==0.4
> charset-normalizer==3.3.2
> colorama==0.4.6
> concurrent-log-handler==0.9.23
> contourpy==1.2.0
> cryptography==42.0.7
> cx_Logging==3.2.0
> cycler==0.12.1
> darkdetect==0.8.0
> decorator==5.1.1
> defusedxml==0.7.1
> Deprecated==1.2.14
> docopt==0.6.2
> executing==2.0.1
> fastjsonschema==2.19.1
> fonttools==4.48.1
> idna==3.7
> ipython==8.12.3
> jedi==0.19.1
> Jinja2==3.1.4
> jsonschema==4.22.0
> jsonschema-specifications==2023.12.1
> jupyter_client==8.6.1
> jupyter_core==5.7.2
> jupyterlab_pygments==0.3.0
> kiwisolver==1.4.5
> kuai_log==0.8
> lief==0.14.1
> markdown2==2.4.13
> MarkupSafe==2.1.5
> matplotlib==3.8.2
> matplotlib-inline==0.1.7
> mistune==3.0.2
> MouseInfo==0.1.3
> nb-log==12.7
> nb_filelock==0.7
> nbclient==0.10.0
> nbconvert==7.16.4
> nbformat==5.10.4
> numpy==2.2.0
> opencv-contrib-python==4.9.0.80
> opencv-python==4.10.0.84
> packaging==23.2
> pandocfilters==1.5.1
> parso==0.8.4
> pefile==2023.2.7
> pickleshare==0.7.5
> pillow==10.2.0
> Pillow-PIL==0.1.dev0
> pipreqs==0.5.0
> pipreqsnb==0.2.4
> platformdirs==4.2.1
> portalocker==2.8.2
> prompt-toolkit==3.0.43
> psutil==5.9.8
> pure-eval==0.2.2
> pyasn1==0.6.0
> pyasn1_modules==0.4.0
> PyAutoGUI==0.9.54
> pycparser==2.22
> PyGetWindow==0.0.9
> Pygments==2.18.0
> pyinstaller==6.5.0
> pyinstaller-hooks-contrib==2024.3
> PyMsgBox==1.0.9
> pynput==1.7.7
> pyparsing==3.1.1
> pyperclip==1.8.2
> PyQt-Fluent-Widgets==1.4.6
> PyQt5==5.15.10
> PyQt5-Frameless-Window==0.3.7
> PyQt5-Qt5==5.15.2
> PyQt5-sip==12.13.0
> PyRect==0.2.0
> PyScreeze==0.1.30
> PySide6==6.6.1
> PySide6-Addons==6.6.1
> PySide6-Essentials==6.6.1
> python-dateutil==2.8.2
> python-json-logger==0.1.10
> pytweening==1.0.7
> pytz==2024.1
> pywin32==308
> pywin32-ctypes==0.2.2
> PyYAML==6.0.1
> pyzmq==26.0.3
> referencing==0.35.1
> requests==2.31.0
> rpds-py==0.18.1
> ruamel.yaml==0.18.6
> ruamel.yaml.clib==0.2.8
> service-identity==24.1.0
> setuptools==69.2.0
> shiboken6==6.6.1
> six==1.16.0
> soupsieve==2.5
> stack-data==0.6.3
> svgwrite==1.4.3
> tinycss2==1.3.0
> tomorrow3==1.1.0
> tornado==6.4
> traitlets==5.14.3
> tzdata==2024.1
> tzlocal==5.2
> urllib3==2.2.1
> wcwidth==0.2.13
> webencodings==0.5.1
> wheel==0.43.0
> wrapt==1.16.0
> yarg==0.1.9
> 

OK我再试一下

**Comment by NaNExist** [comment]
草所以合着必须去吧nb_log的代码里面加代码才能正常是吗
我看那个issue被关闭还以为高版本的nb_log已经修了呢
现在能正常构建了
但是要在CD里面往库文件里面插代码还是太麻烦了，看看有没有什么其他方法能解决这个问题

**Comment by KIYI671** [comment]
> 草所以合着必须去吧nb_log的代码里面加代码才能正常是吗 我看那个issue被关闭还以为高版本的nb_log已经修了呢 现在能正常构建了 但是要在CD里面往库文件里面插代码还是太麻烦了，看看有没有什么其他方法能解决这个问题

对的，我现在在尝试让AI帮我往库文件里面插代码，各自尝试下吧，看看哪边能先出成果

**Comment by NaNExist** [comment]
我修完了
