### ISSUE TITLE
Feature：关于自适应分辨率

### ISSUE THREAD

**Issue by NaNExist** [KIYI671/AhabAssistantLimbusCompany#34]
我个人觉得这个问题其实优先级没有那么高，1080P的分辨率足够了。
首先总不会有人要提高分辨率吧（
关于缩小分辨率，就其他OCR类的开发经验来看。缩小分辨率之后会导致OCR的匹配识别度下降，从而引发更多奇奇怪怪的BUG
所以考虑自适应分辨率这个特性的开发优先级放低，优先先修bug和其他功能

**Comment by NaNExist** [comment]
> > 我个人觉得这个问题其实优先级没有那么高，1080P的分辨率足够了。
> > 首先总不会有人要提高分辨率吧（
> > 关于缩小分辨率，就其他OCR类的开发经验来看。缩小分辨率之后会导致OCR的匹配识别度下降，从而引发更多奇奇怪怪的BUG
> > 所以考虑自适应分辨率这个特性的开发优先级放低，优先先修bug和其他功能
> 
> 诶，不是，不是已经能自选分辨率了吗（虽然只能保证1k和2k应该没啥问题）？这是要一个检测后自适应选择能用的分辨率的功能吗？

就是关于分辨率问题啦，意思就是现有的就行了，其他比如720P没什么必要去做支持。
这个issue是给其他人看的，就不用提一些重复问题了（

**Comment by KIYI671** [comment]
> > > 我个人觉得这个问题其实优先级没有那么高，1080P的分辨率足够了。
> > > 首先总不会有人要提高分辨率吧（
> > > 关于缩小分辨率，就其他OCR类的开发经验来看。缩小分辨率之后会导致OCR的匹配识别度下降，从而引发更多奇奇怪怪的BUG
> > > 所以考虑自适应分辨率这个特性的开发优先级放低，优先先修bug和其他功能
> > 
> > 诶，不是，不是已经能自选分辨率了吗（虽然只能保证1k和2k应该没啥问题）？这是要一个检测后自适应选择能用的分辨率的功能吗？
> 
> 就是关于分辨率问题啦，意思就是现有的就行了，其他比如720P没什么必要去做支持。
> 这个issue是给其他人看的，就不用提一些重复问题了（

其实对于 #28 ，有一个模糊的想法，就是做一个自适配分辨率的功能出来，查看哪个分辨率的识别率最高，然后自动选择并保存对应的分辨率

**Comment by NaNExist** [comment]
> > > > 我个人觉得这个问题其实优先级没有那么高，1080P的分辨率足够了。
> > > > 首先总不会有人要提高分辨率吧（
> > > > 关于缩小分辨率，就其他OCR类的开发经验来看。缩小分辨率之后会导致OCR的匹配识别度下降，从而引发更多奇奇怪怪的BUG
> > > > 所以考虑自适应分辨率这个特性的开发优先级放低，优先先修bug和其他功能
> > > 
> > > 
> > > 诶，不是，不是已经能自选分辨率了吗（虽然只能保证1k和2k应该没啥问题）？这是要一个检测后自适应选择能用的分辨率的功能吗？
> > 
> > 
> > 就是关于分辨率问题啦，意思就是现有的就行了，其他比如720P没什么必要去做支持。
> > 这个issue是给其他人看的，就不用提一些重复问题了（
> 
> 其实对于 #28 ，有一个模糊的想法，就是做一个自适配分辨率的功能出来，查看哪个分辨率的识别率最高，然后自动选择并保存对应的分辨率

感觉肯定是分辨率越高越好，~让大家都上8K屏玩边狱巴士~（逃 ε=ε=ε=┏(゜ロ゜;)┛

**Comment by KIYI671** [comment]
> > > > > 我个人觉得这个问题其实优先级没有那么高，1080P的分辨率足够了。
> > > > > 首先总不会有人要提高分辨率吧（
> > > > > 关于缩小分辨率，就其他OCR类的开发经验来看。缩小分辨率之后会导致OCR的匹配识别度下降，从而引发更多奇奇怪怪的BUG
> > > > > 所以考虑自适应分辨率这个特性的开发优先级放低，优先先修bug和其他功能
> > > > 
> > > > 
> > > > 诶，不是，不是已经能自选分辨率了吗（虽然只能保证1k和2k应该没啥问题）？这是要一个检测后自适应选择能用的分辨率的功能吗？
> > > 
> > > 
> > > 就是关于分辨率问题啦，意思就是现有的就行了，其他比如720P没什么必要去做支持。
> > > 这个issue是给其他人看的，就不用提一些重复问题了（
> > 
> > 其实对于 #28 ，有一个模糊的想法，就是做一个自适配分辨率的功能出来，查看哪个分辨率的识别率最高，然后自动选择并保存对应的分辨率
> 
> 感觉肯定是分辨率越高越好，~让大家都上8K屏玩边狱巴士~（逃 ε=ε=ε=┏(゜ロ゜;)┛

我的屏幕是2k的，实际上一开始准备直接适配2k的，但是考虑到不一定每个人都有2k屏，所以一最终定为了1k，但是预留了多分辨率的位置（实际是懒癌发作，写完1k能跑就坑了，参考直接省略的使用说明）
不过我现在用远程多用户桌面还是习惯用1k的
