### ISSUE TITLE
Bug:Release的pic内容和源码不一致

### ISSUE THREAD

**Issue by NaNExist** [KIYI671/AhabAssistantLimbusCompany#37]
弱弱的问一句
为什么有些图片，如”announcer.png“在release的版本里面有但是源码里面pic/teams下面没有对应的照片
![announcer](https://github.com/user-attachments/assets/96d1ae07-e709-43df-9558-a35427c451cb)

**Comment by KIYI671** [comment]
> 弱弱的问一句
> 为什么有些图片，如”announcer.png“在release的版本里面有但是源码里面pic/teams下面没有对应的照片
> ![announcer](https://github.com/user-attachments/assets/96d1ae07-e709-43df-9558-a35427c451cb)
> 

可能是推送失败，结果以为是推送成功，给忽略了(|||ﾟДﾟ)

**Comment by maosasagawa** [comment]
包括mirror.py:344 release的版本里也没有这张图，然后其他代码里也没有进行保存这张图的操作喵
        # 战斗配队的情况
        if find_and_click_text("participant") or get_pic_position("./pic/teams/total_participants.png"):

**Comment by KIYI671** [comment]
> 包括mirror.py:344 release的版本里也没有这张图，然后其他代码里也没有进行保存这张图的操作喵
>         # 战斗配队的情况
>         if find_and_click_text("participant") or get_pic_position("./pic/teams/total_participants.png"):

这个没啥印象，晚点补上或者修改(|||ﾟДﾟ)
