### ISSUE TITLE
无法启动 窗口拒绝访问

### ISSUE THREAD

**Issue by 114514900** [KIYI671/AhabAssistantLimbusCompany#38]
![屏幕截图 2024-12-10 135832](https://github.com/user-attachments/assets/5033c4fc-53b7-436c-9139-3f27126db0a0)

**Comment by 114514900** [comment]
佬怎解决啊

**Comment by KIYI671** [comment]
> ![屏幕截图 2024-12-10 135832](https://github.com/user-attachments/assets/5033c4fc-53b7-436c-9139-3f27126db0a0)
> 

有没有试过右键，用管理员身份启动？

**Comment by 114514900** [comment]
没我试试

**Comment by 114514900** [comment]
没用

**Comment by 114514900** [comment]
但卸载重装游戏好了

**Comment by 114514900** [comment]
也是麻烦佬了

**Comment by KIYI671** [comment]
> 但卸载重装游戏好了

( ﾟ∀。)

**Comment by 114514900** [comment]
乐
