### ISSUE TITLE
Error when trying to launch AALC

### ISSUE THREAD

**Issue by arraf270** [KIYI671/AhabAssistantLimbusCompany#42]
I'm getting this error when trying to launch the new version of AALC, how do I fix it?

![image](https://github.com/user-attachments/assets/53021692-56ac-4d04-8925-2cfd2f13136d)

**Comment by KIYI671** [comment]
> I'm getting this error when trying to launch the new version of AALC, how do I fix it?
> 
> ![image](https://github.com/user-attachments/assets/53021692-56ac-4d04-8925-2cfd2f13136d)
> 

Sorry, this update used the CD function to package the project for release, but there seems to be a problem and I have deleted this release first. Please use the previous version of AALC first, and wait until it's evening time on my end before returning to my computer to retest the release (which will be about 19 hours later).

**Comment by NaNExist** [comment]
https://github.com/KIYI671/AhabAssistantLimbusCompany/pull/45 We've tried to fix the bug.
A new release will published soon. You can try it later.

**Comment by arraf270** [comment]
Thank you for your hard work ♥️
