### ISSUE TITLE
Feature:Ctrl+Q中断后自动恢复置顶

### ISSUE THREAD

**Issue by NaNExist** [KIYI671/AhabAssistantLimbusCompany#44]
目前是任务正常结束后恢复置顶
但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。
但是我没看相关实现的源码，这一功能在技术上是可行的吗(*/ω＼*)
如果可行可以考虑对这一功能进行支持

**Comment by KIYI671** [comment]
> 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持

好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上

顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错

**Comment by KIYI671** [comment]
> > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > 
> > 
> > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> 
> 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码

昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了

**Comment by NaNExist** [comment]
> > > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > > 
> > > 
> > > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> > 
> > 
> > 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码
> 
> 昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了

看了一眼，有个个人猜想，就是python默认stdout输出是跟着系统走的。那位老哥的系统用的cp1251没有中文编码就炸了

**Comment by KIYI671** [comment]
> > > > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > > > 
> > > > 
> > > > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > > > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> > > 
> > > 
> > > 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码
> > 
> > 
> > 昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了
> 
> 看了一眼，有个个人猜想，就是python默认stdout输出是跟着系统走的。那位老哥的系统用的cp1251没有中文编码就炸了

UTF-8应该是通用的编码，就是现在不知道怎么用它作为默认编码构建

**Comment by NaNExist** [comment]
> > > > > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > > > > 
> > > > > 
> > > > > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > > > > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> > > > 
> > > > 
> > > > 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码
> > > 
> > > 
> > > 昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了
> > 
> > 
> > 看了一眼，有个个人猜想，就是python默认stdout输出是跟着系统走的。那位老哥的系统用的cp1251没有中文编码就炸了
> 
> UTF-8应该是通用的编码，就是现在不知道怎么用它作为默认编码构建

我尝试改了一下，马上pr一个上来

**Comment by NaNExist** [comment]
> > > > > > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > > > > > 
> > > > > > 
> > > > > > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > > > > > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> > > > > 
> > > > > 
> > > > > 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码
> > > > 
> > > > 
> > > > 昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了
> > > 
> > > 
> > > 看了一眼，有个个人猜想，就是python默认stdout输出是跟着系统走的。那位老哥的系统用的cp1251没有中文编码就炸了
> > 
> > 
> > UTF-8应该是通用的编码，就是现在不知道怎么用它作为默认编码构建
> 
> 我尝试改了一下，马上pr一个上来

失败了，悲QAQ。
感觉这个bug不好修，还有可能有新的bug.比如有不支持utf-8编码的系统怎么办。
或者把log的输出内容全改成英文？

**Comment by KIYI671** [comment]
> > > > > > > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > > > > > > 
> > > > > > > 
> > > > > > > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > > > > > > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> > > > > > 
> > > > > > 
> > > > > > 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码
> > > > > 
> > > > > 
> > > > > 昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了
> > > > 
> > > > 
> > > > 看了一眼，有个个人猜想，就是python默认stdout输出是跟着系统走的。那位老哥的系统用的cp1251没有中文编码就炸了
> > > 
> > > 
> > > UTF-8应该是通用的编码，就是现在不知道怎么用它作为默认编码构建
> > 
> > 
> > 我尝试改了一下，马上pr一个上来
> 
> 失败了，悲QAQ。 感觉这个bug不好修，还有可能有新的bug.比如有不支持utf-8编码的系统怎么办。 或者把log的输出内容全改成英文？

这个bug很奇怪，我手动打包的反倒是没有出问题

**Comment by KIYI671** [comment]
> > > > > > > > > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > > > > > > > > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码
> > > > > > > 
> > > > > > > 
> > > > > > > 昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了
> > > > > > 
> > > > > > 
> > > > > > 看了一眼，有个个人猜想，就是python默认stdout输出是跟着系统走的。那位老哥的系统用的cp1251没有中文编码就炸了
> > > > > 
> > > > > 
> > > > > UTF-8应该是通用的编码，就是现在不知道怎么用它作为默认编码构建
> > > > 
> > > > 
> > > > 我尝试改了一下，马上pr一个上来
> > > 
> > > 
> > > 失败了，悲QAQ。 感觉这个bug不好修，还有可能有新的bug.比如有不支持utf-8编码的系统怎么办。 或者把log的输出内容全改成英文？
> > 
> > 
> > 这个bug很奇怪，我手动打包的反倒是没有出问题
> 
> 感觉是因为额外修了nb_log库的那几行代码问题，我再看看

你试试能不能修，我先发一版让那位俄语老哥试试

**Comment by NaNExist** [comment]
> > > > > > > > > > > 目前是任务正常结束后恢复置顶 但是有些时候出了bug需要调试，或者单纯设置一个很大的重复数来一直下牢，需要中断时。这时置顶不会自动恢复，如果能实现中断时也能自动恢复置顶会提升体验。 但是我没看相关实现的源码，这一功能在技术上是可行的吗(_/ω＼_) 如果可行可以考虑对这一功能进行支持
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 好了，虽然忘记是怎么做到强制中断的，但是幸好留了个改文字的功能，刚好给加上
> > > > > > > > > > 顺便，你对于 #42 的问题处理有头绪吗？这位老哥看起来是俄语区的，使用CD构建的程序他运行会因为编码问题报错，看起来是日志库nb_log的问题，但是目前没想到解决方法，不知道如果对库降级会不会有用
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 好的我晚上看看这个问题 顺便可以考虑最近发一个正式版看看bug到底是由什么引入的cd流程还是改的代码
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 昨晚睡前发了一个正式版，然后还没睡着老哥就来发issues了
> > > > > > > 
> > > > > > > 
> > > > > > > 看了一眼，有个个人猜想，就是python默认stdout输出是跟着系统走的。那位老哥的系统用的cp1251没有中文编码就炸了
> > > > > > 
> > > > > > 
> > > > > > UTF-8应该是通用的编码，就是现在不知道怎么用它作为默认编码构建
> > > > > 
> > > > > 
> > > > > 我尝试改了一下，马上pr一个上来
> > > > 
> > > > 
> > > > 失败了，悲QAQ。 感觉这个bug不好修，还有可能有新的bug.比如有不支持utf-8编码的系统怎么办。 或者把log的输出内容全改成英文？
> > > 
> > > 
> > > 这个bug很奇怪，我手动打包的反倒是没有出问题
> > 
> > 
> > 感觉是因为额外修了nb_log库的那几行代码问题，我再看看
> 
> 你试试能不能修，我先发一版让那位俄语老哥试试

https://github.com/KIYI671/AhabAssistantLimbusCompany/pull/45 已经pr了
