### ISSUE TITLE
商店购物摸扩错误

### ISSUE THREAD

**Issue by Qianbai2035** [KIYI671/AhabAssistantLimbusCompany#5]
我无法准确的判断该问题因为什么触发，但AALC在第四层BOSS前的休息点卡住了，一直在购买恢复的次级页面，看得出来鼠标想点恢复所有人的体力，但因全体罪人为满血而不断重复，无法触发下一步。
手动在程序点击间隔后，点击第三选项-不需要恢复，该循环中断，并执行强化饰品的步骤。

**Comment by KIYI671** [comment]
> 我无法准确的判断该问题因为什么触发，但AALC在第四层BOSS前的休息点卡住了，一直在购买恢复的次级页面，看得出来鼠标想点恢复所有人的体力，但因全体罪人为满血而不断重复，无法触发下一步。 手动在程序点击间隔后，点击第三选项-不需要恢复，该循环中断，并执行强化饰品的步骤。

代码里有这个情况的处理预案，但是似乎没有生效，姑且试着改了下处理方式，脑测大概能过，目前这种情况还是很少遇到，所以等下次再一起更新进来

**Comment by KIYI671** [comment]
此问题已经修复，请前往release下载新的脚本程序更新

**Comment by KIYI671** [comment]
你好，请重新前往release下载新的脚本程序更新，之前的修复，只有脑测通过，没有实际测试，会在遇到这个情况时报错、退出脚本，现在已经重新修复
