### ISSUE TITLE
Feature:镜牢商店逻辑优化

### ISSUE THREAD

**Issue by NaNExist** [KIYI671/AhabAssistantLimbusCompany#52]
注意到镜牢的商店事件中购买饰品的代码
https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/mirror.py#L298-L301
使用if判断来检测，使得每次进入商店实际上只会刷新一次。
很多情况下到结束也会有大量钱留着没花，感觉这里的逻辑可以优化一下（比如一直刷新到没钱刷新或者低于一个阈值？

**Comment by KIYI671** [comment]
> 注意到镜牢的商店事件中购买饰品的代码
> 
> https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/mirror.py#L298-L301
> 
> 
> 使用if判断来检测，使得每次进入商店实际上只会刷新一次。
> 很多情况下到结束也会有大量钱留着没花，感觉这里的逻辑可以优化一下（比如一直刷新到没钱刷新或者低于一个阈值？

实际上是选了免费刷新星光加成才有一次，你觉得阈值多少合适？500？

**Comment by NaNExist** [comment]
> > 注意到镜牢的商店事件中购买饰品的代码
> > https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/mirror.py#L298-L301
> > 
> > 使用if判断来检测，使得每次进入商店实际上只会刷新一次。
> > 很多情况下到结束也会有大量钱留着没花，感觉这里的逻辑可以优化一下（比如一直刷新到没钱刷新或者低于一个阈值？
> 
> 实际上是选了免费刷新星光加成才有一次，你觉得阈值多少合适？500？

感觉阈值不好定，比如到五层了我肯定是想全部花光，但是这还要检测层数有点麻烦。大概就定至少还能买得起一个藏品，防止刷新出来没钱买？
然后把像升级饰品的花钱操作放在前面，同时买到一个藏品就升级，这样会不会好一点？

**Comment by KIYI671** [comment]
> > > 注意到镜牢的商店事件中购买饰品的代码
> > > https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/mirror.py#L298-L301
> > > 
> > > 使用if判断来检测，使得每次进入商店实际上只会刷新一次。
> > > 很多情况下到结束也会有大量钱留着没花，感觉这里的逻辑可以优化一下（比如一直刷新到没钱刷新或者低于一个阈值？
> > 
> > 
> > 实际上是选了免费刷新星光加成才有一次，你觉得阈值多少合适？500？
> 
> 感觉阈值不好定，比如到五层了我肯定是想全部花光，但是这还要检测层数有点麻烦。大概就定至少还能买得起一个藏品，防止刷新出来没钱买？ 然后把像升级饰品的花钱操作放在前面，同时买到一个藏品就升级，这样会不会好一点？

我试一下，晚点更新，到时候你看看

**Comment by KIYI671** [comment]
> > > 注意到镜牢的商店事件中购买饰品的代码
> > > https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/mirror.py#L298-L301
> > > 
> > > 使用if判断来检测，使得每次进入商店实际上只会刷新一次。
> > > 很多情况下到结束也会有大量钱留着没花，感觉这里的逻辑可以优化一下（比如一直刷新到没钱刷新或者低于一个阈值？
> > 
> > 
> > 实际上是选了免费刷新星光加成才有一次，你觉得阈值多少合适？500？
> 
> 感觉阈值不好定，比如到五层了我肯定是想全部花光，但是这还要检测层数有点麻烦。大概就定至少还能买得起一个藏品，防止刷新出来没钱买？ 然后把像升级饰品的花钱操作放在前面，同时买到一个藏品就升级，这样会不会好一点？

想了想，还是只花钱买，不升级比较好，现在升级还是太耗时了

**Comment by NaNExist** [comment]
那就先这样，进一步优化就以后再说吧
不过从一开始设置为第一层的逻辑对于道中才开始的镜牢任务就不行了，但是反正这样也能跑就这样了(´・ω・)つ

**Comment by KIYI671** [comment]
> 那就先这样，进一步优化就以后再说吧 不过从一开始设置为第一层的逻辑对于道中才开始的镜牢任务就不行了，但是反正这样也能跑就这样了(´・ω・)つ

有考虑过设置金钱阈值，但是需要用到OCR，现在一把50+分钟已经比较慢了，还是减少拖延的时间吧（其实感觉4层消费比较合适，因为第五层只剩下BOSS了，待会改成四层吧）

**Comment by NaNExist** [comment]
> > 那就先这样，进一步优化就以后再说吧 不过从一开始设置为第一层的逻辑对于道中才开始的镜牢任务就不行了，但是反正这样也能跑就这样了(´・ω・)つ
> 
> 有考虑过设置金钱阈值，但是需要用到OCR，现在一把50+分钟已经比较慢了，还是减少拖延的时间吧（其实感觉4层消费比较合适，因为第五层只剩下BOSS了，待会改成四层吧）

一把50+分钟感觉已经很快了，体感自己手打也要一个小时还要盯着看。AALC已经很大解放双手了（
不知道时间占比最大的是哪一部分，看看还有没有能优化的

**Comment by KIYI671** [comment]
> > > 那就先这样，进一步优化就以后再说吧 不过从一开始设置为第一层的逻辑对于道中才开始的镜牢任务就不行了，但是反正这样也能跑就这样了(´・ω・)つ
> > 
> > 
> > 有考虑过设置金钱阈值，但是需要用到OCR，现在一把50+分钟已经比较慢了，还是减少拖延的时间吧（其实感觉4层消费比较合适，因为第五层只剩下BOSS了，待会改成四层吧）
> 
> 一把50+分钟感觉已经很快了，体感自己手打也要一个小时还要盯着看。AALC已经很大解放双手了（ 不知道时间占比最大的是哪一部分，看看还有没有能优化的

是战斗动画！（即答
可以在项目debug时添加一些计时器，看看哪部分比较久

**Comment by NaNExist** [comment]
> > > > 那就先这样，进一步优化就以后再说吧 不过从一开始设置为第一层的逻辑对于道中才开始的镜牢任务就不行了，但是反正这样也能跑就这样了(´・ω・)つ
> > > 
> > > 
> > > 有考虑过设置金钱阈值，但是需要用到OCR，现在一把50+分钟已经比较慢了，还是减少拖延的时间吧（其实感觉4层消费比较合适，因为第五层只剩下BOSS了，待会改成四层吧）
> > 
> > 
> > 一把50+分钟感觉已经很快了，体感自己手打也要一个小时还要盯着看。AALC已经很大解放双手了（ 不知道时间占比最大的是哪一部分，看看还有没有能优化的
> 
> 是战斗动画！（即答 可以在项目debug时添加一些计时器，看看哪部分比较久

那我之后看看加点计时器(ﾟ∀。)
