### ISSUE TITLE
Bug:默认缩放比例问题

### ISSUE THREAD

**Issue by NaNExist** [KIYI671/AhabAssistantLimbusCompany#53]
请问一下为什么
```python
scale_factors = [0.75, 1.0, 0.5, 0.625, 1.25, 1.5]
    if environ.get('window_size'):
        scale = int(environ.get('window_size'))
```
要选用 ```[0.75, 1.0, 0.5, 0.625, 1.25, 1.5]``` 为缩放系数呢？
同时debug发现 ```environ.get('window_size')``` 返回的是0，缩放系数一直是0.75，这是预期行为吗？
```
2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0
2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前缩放比例0.75
```

下午不知道为什么卡在镜牢开始的位置识别不到 Enter 了,还是出现在正常刷完一遍之后关闭了AALC再重新打开的时候
```
2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:54" - my_log - INFO - 结束执行 返回主界面
2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/drive_features.png的位置)
2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/init_drive.png的中心点在截屏的位置:(1312,944)
2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(1320,938)
2024-12-14 17:10:31 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/drive_features.png的中心点在截屏的位置:(1694,218)
2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/mirror_dungeons.png的中心点在截屏的位置:(669,514)
2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(673,512)
2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置)
2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_normal_mirror.png的位置)
2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/resume_mir.png的位置)
2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/total_progress.png的位置)
2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/mirror_select_theme_pack.png的位置)
```
感觉问题有点像https://github.com/KIYI671/AhabAssistantLimbusCompany/issues/28

**Comment by KIYI671** [comment]
> 请问一下为什么
> 
> ```python
> scale_factors = [0.75, 1.0, 0.5, 0.625, 1.25, 1.5]
>     if environ.get('window_size'):
>         scale = int(environ.get('window_size'))
> ```
> 
> 要选用 `[0.75, 1.0, 0.5, 0.625, 1.25, 1.5]` 为缩放系数呢？ 同时debug发现 `environ.get('window_size')` 返回的是0，缩放系数一直是0.75，这是预期行为吗？
> 
> ```
> 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0
> 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前缩放比例0.75
> ```
> 
> 下午不知道为什么卡在镜牢开始的位置识别不到 Enter 了,还是出现在正常刷完一遍之后关闭了AALC再重新打开的时候
> 
> ```
> 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:54" - my_log - INFO - 结束执行 返回主界面
> 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/drive_features.png的位置)
> 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/init_drive.png的中心点在截屏的位置:(1312,944)
> 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(1320,938)
> 2024-12-14 17:10:31 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/drive_features.png的中心点在截屏的位置:(1694,218)
> 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/mirror_dungeons.png的中心点在截屏的位置:(669,514)
> 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(673,512)
> 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置)
> 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_normal_mirror.png的位置)
> 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/resume_mir.png的位置)
> 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/total_progress.png的位置)
> 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/mirror_select_theme_pack.png的位置)
> ```
> 
> 感觉问题有点像#28

因为一开始还没做多分辨率识别时，只支持1920*1080，而我又预留了多分辨率识别功能实现的可能性，所以默认为0.75开头

environ.get('window_size')的获取值，在
[        environ['window_size'] = f"{win_size}"](https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/script_task_scheme.py#L131C1-L131C47)
获取了
通过environ设置为写入环境中，使得能够在各个py文件中读取

识别不到的情况有点奇怪，我昨天也遇到了点击错位的情况，晚点试试能不能搞个尝试处理的方法

**Comment by NaNExist** [comment]
> > 请问一下为什么
> > ```python
> > scale_factors = [0.75, 1.0, 0.5, 0.625, 1.25, 1.5]
> >     if environ.get('window_size'):
> >         scale = int(environ.get('window_size'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 要选用 `[0.75, 1.0, 0.5, 0.625, 1.25, 1.5]` 为缩放系数呢？ 同时debug发现 `environ.get('window_size')` 返回的是0，缩放系数一直是0.75，这是预期行为吗？
> > ```
> > 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0
> > 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前缩放比例0.75
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 下午不知道为什么卡在镜牢开始的位置识别不到 Enter 了,还是出现在正常刷完一遍之后关闭了AALC再重新打开的时候
> > ```
> > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:54" - my_log - INFO - 结束执行 返回主界面
> > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/drive_features.png的位置)
> > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/init_drive.png的中心点在截屏的位置:(1312,944)
> > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(1320,938)
> > 2024-12-14 17:10:31 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/drive_features.png的中心点在截屏的位置:(1694,218)
> > 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/mirror_dungeons.png的中心点在截屏的位置:(669,514)
> > 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(673,512)
> > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置)
> > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_normal_mirror.png的位置)
> > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/resume_mir.png的位置)
> > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/total_progress.png的位置)
> > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/mirror_select_theme_pack.png的位置)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 感觉问题有点像#28
> 
> 因为一开始还没做多分辨率识别时，只支持1920*1080，而我又预留了多分辨率识别功能实现的可能性，所以默认为0.75开头
> 
> environ.get('window_size')的获取值，在 [ environ['window_size'] = f"{win_size}"](https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/script_task_scheme.py#L131C1-L131C47) 获取了 通过environ设置为写入环境中，使得能够在各个py文件中读取
> 
> 识别不到的情况有点奇怪，我昨天也遇到了点击错位的情况，晚点试试能不能搞个尝试处理的方法

使用0.75的系数是出于性能上的考虑吗？如果使用1会不会匹配度更高一点

**Comment by KIYI671** [comment]
> > > 请问一下为什么
> > > ```python
> > > scale_factors = [0.75, 1.0, 0.5, 0.625, 1.25, 1.5]
> > >     if environ.get('window_size'):
> > >         scale = int(environ.get('window_size'))
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 要选用 `[0.75, 1.0, 0.5, 0.625, 1.25, 1.5]` 为缩放系数呢？ 同时debug发现 `environ.get('window_size')` 返回的是0，缩放系数一直是0.75，这是预期行为吗？
> > > ```
> > > 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0
> > > 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前缩放比例0.75
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 下午不知道为什么卡在镜牢开始的位置识别不到 Enter 了,还是出现在正常刷完一遍之后关闭了AALC再重新打开的时候
> > > ```
> > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:54" - my_log - INFO - 结束执行 返回主界面
> > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/drive_features.png的位置)
> > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/init_drive.png的中心点在截屏的位置:(1312,944)
> > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(1320,938)
> > > 2024-12-14 17:10:31 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/drive_features.png的中心点在截屏的位置:(1694,218)
> > > 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/mirror_dungeons.png的中心点在截屏的位置:(669,514)
> > > 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(673,512)
> > > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置)
> > > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> > > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_normal_mirror.png的位置)
> > > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/resume_mir.png的位置)
> > > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/total_progress.png的位置)
> > > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/mirror_select_theme_pack.png的位置)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 感觉问题有点像#28
> > 
> > 
> > 因为一开始还没做多分辨率识别时，只支持1920*1080，而我又预留了多分辨率识别功能实现的可能性，所以默认为0.75开头
> > environ.get('window_size')的获取值，在 [ environ['window_size'] = f"{win_size}"](https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/script_task_scheme.py#L131C1-L131C47) 获取了 通过environ设置为写入环境中，使得能够在各个py文件中读取
> > 识别不到的情况有点奇怪，我昨天也遇到了点击错位的情况，晚点试试能不能搞个尝试处理的方法
> 
> 使用0.75的系数是出于性能上的考虑吗？如果使用1会不会匹配度更高一点 而且cv2.resize的fx参数是原始大小乘上缩放因子吧，那1080P*0.75,2K却是乘1？

不是，这个系数与性能无关，就是用于适配我分辨率的。
匹配度阈值在函数默认参数设置了，为0.8
cv2.resize的fx参数这个，我使用的用于图像识别的截图一直是2560*1440下截的图，所以如果要适配1920*1080，需要把用于识别的图片缩小，这里实际是1440*0.75=1080

**Comment by NaNExist** [comment]
> > > > 请问一下为什么
> > > > ```python
> > > > scale_factors = [0.75, 1.0, 0.5, 0.625, 1.25, 1.5]
> > > >     if environ.get('window_size'):
> > > >         scale = int(environ.get('window_size'))
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 要选用 `[0.75, 1.0, 0.5, 0.625, 1.25, 1.5]` 为缩放系数呢？ 同时debug发现 `environ.get('window_size')` 返回的是0，缩放系数一直是0.75，这是预期行为吗？
> > > > ```
> > > > 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0
> > > > 2024-12-14 17:41:22 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前缩放比例0.75
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 下午不知道为什么卡在镜牢开始的位置识别不到 Enter 了,还是出现在正常刷完一遍之后关闭了AALC再重新打开的时候
> > > > ```
> > > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:54" - my_log - INFO - 结束执行 返回主界面
> > > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/drive_features.png的位置)
> > > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/init_drive.png的中心点在截屏的位置:(1312,944)
> > > > 2024-12-14 17:10:30 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(1320,938)
> > > > 2024-12-14 17:10:31 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/drive_features.png的中心点在截屏的位置:(1694,218)
> > > > 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/scenes/mirror_dungeons.png的中心点在截屏的位置:(669,514)
> > > > 2024-12-14 17:10:32 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(673,512)
> > > > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置)
> > > > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> > > > 2024-12-14 17:10:33 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_normal_mirror.png的位置)
> > > > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/resume_mir.png的位置)
> > > > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/total_progress.png的位置)
> > > > 2024-12-14 17:10:34 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/scenes/mirror_select_theme_pack.png的位置)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 感觉问题有点像#28
> > > 
> > > 
> > > 因为一开始还没做多分辨率识别时，只支持1920*1080，而我又预留了多分辨率识别功能实现的可能性，所以默认为0.75开头
> > > environ.get('window_size')的获取值，在 [ environ['window_size'] = f"{win_size}"](https://github.com/KIYI671/AhabAssistantLimbusCompany/blob/da81614c9b573b8d49336a5cca1d9471746887e6/script/script_task_scheme.py#L131C1-L131C47) 获取了 通过environ设置为写入环境中，使得能够在各个py文件中读取
> > > 识别不到的情况有点奇怪，我昨天也遇到了点击错位的情况，晚点试试能不能搞个尝试处理的方法
> > 
> > 
> > 使用0.75的系数是出于性能上的考虑吗？如果使用1会不会匹配度更高一点 而且cv2.resize的fx参数是原始大小乘上缩放因子吧，那1080P*0.75,2K却是乘1？
> 
> 不是，这个系数与性能无关，就是用于适配多分辨率的。 匹配度阈值在函数默认参数设置了，为0.8 cv2.resize的fx参数这个，我使用的用于图像识别的截图一直是2560_1440下截的图，所以如果要适配1920_1080，需要把用于识别的图片缩小，这里实际是1440*0.75=1080

好吧，我看看能不能在ocr的流程中多添加一点debug消息，看看能不能定位为什么抽风

**Comment by KIYI671** [comment]
> 
> 好吧，我看看能不能在ocr的流程中多添加一点debug消息，看看能不能定位为什么抽风

OCR毕竟耗时，所以更多的识别还是用的图像识别，包括镜牢开始的位置

**Comment by NaNExist** [comment]
> > 好吧，我看看能不能在ocr的流程中多添加一点debug消息，看看能不能定位为什么抽风
> 
> OCR毕竟耗时，所以更多的识别还是用的图像识别，包括镜牢开始的位置

感觉是阈值有时候太高了...?
```
2024-12-14 18:52:19 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(664,518)
2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0,当前缩放比例0.75
2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置,最大相似度0.726144552230835
2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
```
抓出来的log 是这样的,是不是从0.8向下调一些？

**Comment by KIYI671** [comment]
> > > 好吧，我看看能不能在ocr的流程中多添加一点debug消息，看看能不能定位为什么抽风
> > 
> > 
> > OCR毕竟耗时，所以更多的识别还是用的图像识别，包括镜牢开始的位置
> 
> 感觉是阈值有时候太高了...?
> 
> ```
> 2024-12-14 18:52:19 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(664,518)
> 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0,当前缩放比例0.75
> 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置,最大相似度0.726144552230835
> 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> ```
> 
> 抓出来的log 是这样的,是不是从0.8向下调一些？

0.8是比较好用的正常范围，因为你不知道调低阈值的话，会识别出什么妖魔鬼怪
而且正常不会这样的
我看你日志应该是还能复现？试试alt+enter将游戏全屏后再启动试试

**Comment by NaNExist** [comment]
> > > > 好吧，我看看能不能在ocr的流程中多添加一点debug消息，看看能不能定位为什么抽风
> > > 
> > > 
> > > OCR毕竟耗时，所以更多的识别还是用的图像识别，包括镜牢开始的位置
> > 
> > 
> > 感觉是阈值有时候太高了...?
> > ```
> > 2024-12-14 18:52:19 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(664,518)
> > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0,当前缩放比例0.75
> > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置,最大相似度0.726144552230835
> > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 抓出来的log 是这样的,是不是从0.8向下调一些？
> 
> 0.8是比较好用的正常范围，因为你不知道调低阈值的话，会识别出什么妖魔鬼怪 而且正常不会这样的 我看你日志应该是还能复现？试试alt+enter将游戏全屏后再启动试试

alt+enter将游戏全屏后再启动问题就消除了
所以这个bug是怎么出现的，感觉得修一修
```
2024-12-14 19:01:29 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/mirror/enter_mirror_button.png的中心点在截屏的位置:(1641,741),相似度为0.9473034143447876
```

**Comment by KIYI671** [comment]
> > > > > 好吧，我看看能不能在ocr的流程中多添加一点debug消息，看看能不能定位为什么抽风
> > > > 
> > > > 
> > > > OCR毕竟耗时，所以更多的识别还是用的图像识别，包括镜牢开始的位置
> > > 
> > > 
> > > 感觉是阈值有时候太高了...?
> > > ```
> > > 2024-12-14 18:52:19 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(664,518)
> > > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0,当前缩放比例0.75
> > > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置,最大相似度0.726144552230835
> > > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 抓出来的log 是这样的,是不是从0.8向下调一些？
> > 
> > 
> > 0.8是比较好用的正常范围，因为你不知道调低阈值的话，会识别出什么妖魔鬼怪 而且正常不会这样的 我看你日志应该是还能复现？试试alt+enter将游戏全屏后再启动试试
> 
> alt+enter将游戏全屏后再启动问题就消除了 所以这个bug是怎么出现的，感觉得修一修
> 
> ```
> 2024-12-14 19:01:29 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/mirror/enter_mirror_button.png的中心点在截屏的位置:(1641,741),相似度为0.9473034143447876
> ```

感觉可能是消去任务栏的后遗症，你可以看看我刚刚推送的更新，加了一步重置窗口的功能

**Comment by NaNExist** [comment]
> > > > > > 好吧，我看看能不能在ocr的流程中多添加一点debug消息，看看能不能定位为什么抽风
> > > > > 
> > > > > 
> > > > > OCR毕竟耗时，所以更多的识别还是用的图像识别，包括镜牢开始的位置
> > > > 
> > > > 
> > > > 感觉是阈值有时候太高了...?
> > > > ```
> > > > 2024-12-14 18:52:19 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 点击位置:(664,518)
> > > > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 当前窗口大小0,当前缩放比例0.75
> > > > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 未能获取到图片./pic/mirror/enter_mirror_button.png的位置,最大相似度0.726144552230835
> > > > 2024-12-14 18:52:20 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 传入位置为空，无法进行点击
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 抓出来的log 是这样的,是不是从0.8向下调一些？
> > > 
> > > 
> > > 0.8是比较好用的正常范围，因为你不知道调低阈值的话，会识别出什么妖魔鬼怪 而且正常不会这样的 我看你日志应该是还能复现？试试alt+enter将游戏全屏后再启动试试
> > 
> > 
> > alt+enter将游戏全屏后再启动问题就消除了 所以这个bug是怎么出现的，感觉得修一修
> > ```
> > 2024-12-14 19:01:29 - debugLogger - "my_log\my_log.py:52" - my_log - DEBUG - 获取到图片./pic/mirror/enter_mirror_button.png的中心点在截屏的位置:(1641,741),相似度为0.9473034143447876
> > ```
> 
> 感觉可能是消去任务栏的后遗症，你可以看看我刚刚推送的更新，加了一步重置窗口的功能

那就这样吧
