### ISSUE TITLE
各个版本都卡在镜牢开始界面不动

### ISSUE THREAD

**Issue by pevoku** [KIYI671/AhabAssistantLimbusCompany#57]
试过最近的几个版本都是在进入镜牢界面卡柱不动了

**Comment by KIYI671** [comment]
> 试过最近的几个版本都是在进入镜牢界面卡柱不动了

具体是卡在哪里？有截图和日志吗？

**Comment by NaNExist** [comment]
窗口重置那个补丁修完之后好像还没发过release
请先尝试alt+enter将游戏全屏后再启动，看看问题是否消除
或者等待稍晚些时候的最新版本

**Comment by pevoku** [comment]
> 窗口重置那个补丁修完之后好像还没发过release 请先尝试alt+enter将游戏全屏后再启动，看看问题是否消除 或者等待稍晚些时候的最新版本

把自动调节窗口设置关掉之后能正常进镜牢了，但是之后又是卡在商店界面
![screenshot](https://github.com/user-attachments/assets/28bcfeb7-0b38-445d-a599-dfeb005ac80b)

**Comment by KIYI671** [comment]
> > 窗口重置那个补丁修完之后好像还没发过release 请先尝试alt+enter将游戏全屏后再启动，看看问题是否消除 或者等待稍晚些时候的最新版本
> 
> 把自动调节窗口设置关掉之后能正常进镜牢了，但是之后又是卡在商店界面 ![screenshot](https://private-user-images.githubusercontent.com/159112875/395863411-28bcfeb7-0b38-445d-a599-dfeb005ac80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjgwMzcsIm5iZiI6MTczNDI2NzczNywicGF0aCI6Ii8xNTkxMTI4NzUvMzk1ODYzNDExLTI4YmNmZWI3LTBiMzgtNDQ1ZC1hNTk5LWRmZWIwMDVhYzgwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxMzAyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmJiYWRiMTVkNWViMWIzOTNmYTBhMGM0YjU1YzMzYjgxZmU4NjA0MTY5ZGFhY2E2YTljYmJlZjAwOWIxNmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.K99Mm8LyKXerMMmD4S4Egzk9Z-9fF14N49E4zFuKNcU)

这种情况的话，请发一下日志，目前仅靠截屏，有点难以判断，只能猜测是商店离开按钮识别问题

**Comment by pevoku** [comment]
[2024-12-15.0001.debugLog.log](https://github.com/user-attachments/files/18140493/2024-12-15.0001.debugLog.log)

**Comment by KIYI671** [comment]
> [2024-12-15.0001.debugLog.log](https://github.com/user-attachments/files/18140493/2024-12-15.0001.debugLog.log)

新版添加了“离开商店时重复识别，保证离开渠道”的功能，请等待稍晚些时候的最新版本

还有什么问题或者建议吗，一起提出来好修改

**Comment by pevoku** [comment]
> > [2024-12-15.0001.debugLog.log](https://github.com/user-attachments/files/18140493/2024-12-15.0001.debugLog.log)
> 
> 新版添加了“离开商店时重复识别，保证离开渠道”的功能，请等待稍晚些时候的最新版本
> 
> 还有什么问题或者建议吗，一起提出来好修改

一直用着流血队打的，基本强化完饰品就能正常打过 目前感觉有些难受的还是一个效率（昨晚上看日志是1小时多打一把普牢）和卡在某个界面不动了
很多时候卡在一些莫名的位置 比如昨晚上刷完一把牢之后就也卡在第二把开始选择队伍上 在这些位置都加上重复判断的操作？

**Comment by pevoku** [comment]
今晚上再挂一晚上 要是有其他问题就再发一遍日志

**Comment by KIYI671** [comment]
> > > [2024-12-15.0001.debugLog.log](https://github.com/user-attachments/files/18140493/2024-12-15.0001.debugLog.log)
> > 
> > 
> > 新版添加了“离开商店时重复识别，保证离开渠道”的功能，请等待稍晚些时候的最新版本
> > 还有什么问题或者建议吗，一起提出来好修改
> 
> 一直用着流血队打的，基本强化完饰品就能正常打过 目前感觉有些难受的还是一个效率（昨晚上看日志是1小时多打一把普牢）和卡在某个界面不动了 很多时候卡在一些莫名的位置 比如昨晚上刷完一把牢之后就也卡在第二把开始选择队伍上 在这些位置都加上重复判断的操作？

已发布V0.1.6版本，等github自动打包上传后可以更新使用

**Comment by pevoku** [comment]
今晚挂着刷一晚上 有问题明天再发一遍日志

**Comment by pevoku** [comment]
> > > > [2024-12-15.0001.debugLog.log](https://github.com/user-attachments/files/18140493/2024-12-15.0001.debugLog.log)
> > > 
> > > 
> > > 新版添加了“离开商店时重复识别，保证离开渠道”的功能，请等待稍晚些时候的最新版本
> > > 还有什么问题或者建议吗，一起提出来好修改
> > 
> > 
> > 一直用着流血队打的，基本强化完饰品就能正常打过 目前感觉有些难受的还是一个效率（昨晚上看日志是1小时多打一把普牢）和卡在某个界面不动了 很多时候卡在一些莫名的位置 比如昨晚上刷完一把牢之后就也卡在第二把开始选择队伍上 在这些位置都加上重复判断的操作？
> 
> 已发布V0.1.6版本，等github自动打包上传后可以更新使用

2024-12-15 23:37:33 - debugLogger - "my_log\my_log.py:66" - my_log - ERROR - 'float' object cannot be interpreted as an integer
还是卡在镜牢门口，alt+enter再开启也一样

**Comment by KIYI671** [comment]
> > > > > [2024-12-15.0001.debugLog.log](https://github.com/user-attachments/files/18140493/2024-12-15.0001.debugLog.log)
> > > > 
> > > > 
> > > > 新版添加了“离开商店时重复识别，保证离开渠道”的功能，请等待稍晚些时候的最新版本
> > > > 还有什么问题或者建议吗，一起提出来好修改
> > > 
> > > 
> > > 一直用着流血队打的，基本强化完饰品就能正常打过 目前感觉有些难受的还是一个效率（昨晚上看日志是1小时多打一把普牢）和卡在某个界面不动了 很多时候卡在一些莫名的位置 比如昨晚上刷完一把牢之后就也卡在第二把开始选择队伍上 在这些位置都加上重复判断的操作？
> > 
> > 
> > 已发布V0.1.6版本，等github自动打包上传后可以更新使用
> 
> 2024-12-15 23:37:33 - debugLogger - "my_log\my_log.py:66" - my_log - ERROR - 'float' object cannot be interpreted as an integer 还是卡在镜牢门口，alt+enter再开启也一样

请发整份log吧，好定位问题

**Comment by pevoku** [comment]
[logs.zip](https://github.com/user-attachments/files/18141083/logs.zip)

**Comment by KIYI671** [comment]
> [logs.zip](https://github.com/user-attachments/files/18141083/logs.zip)

是否还未上传完成？压缩包只有4K，且无法打开

**Comment by pevoku** [comment]
我再传一次
[logs.zip](https://github.com/user-attachments/files/18141092/logs.zip)

**Comment by KIYI671** [comment]
> 我再传一次 [logs.zip](https://github.com/user-attachments/files/18141092/logs.zip)

定位到问题了，请待会下载V0.1.6.1版本，应该没问题了

**Comment by pevoku** [comment]
昨晚的问题是打到第四层第五层的时候 地图被缩放到最小然后卡住不动了
[2024-12-16.0001.debugLog.log](https://github.com/user-attachments/files/18143006/2024-12-16.0001.debugLog.log)

**Comment by KIYI671** [comment]
> 昨晚的问题是打到第四层第五层的时候 地图被缩放到最小然后卡住不动了
> [2024-12-16.0001.debugLog.log](https://github.com/user-attachments/files/18143006/2024-12-16.0001.debugLog.log)
> 

今晚再看看

**Comment by pevoku** [comment]
第四层的时候手动放大后正常执行 第五层重复出现就没继续运行下去了
这个问题之前的版本也会时常出现

**Comment by KIYI671** [comment]
> 第四层的时候手动放大后正常执行 第五层重复出现就没继续运行下去了
> 这个问题之前的版本也会时常出现

这本来是一个保障程序继续运行的措施，但是似乎失效还导致出错了

**Comment by KIYI671** [comment]
> 昨晚的问题是打到第四层第五层的时候 地图被缩放到最小然后卡住不动了 [2024-12-16.0001.debugLog.log](https://github.com/user-attachments/files/18143006/2024-12-16.0001.debugLog.log)

不明白具体情况，但是下个版本更新将补完缩小寻路的逻辑，并添加走投无路时越狱重进功能

**Comment by pevoku** [comment]
大概是什么时候能更新？晚上挂一晚上测测

**Comment by KIYI671** [comment]
> 大概是什么时候能更新？晚上挂一晚上测测

我先自己测试下，大概会在12点前

**Comment by pevoku** [comment]
老大加油喵

**Comment by pevoku** [comment]
老大加油喵

**Comment by pevoku** [comment]
新版本怎么样了？ 今晚还挂的成吗

**Comment by pevoku** [comment]
[2024-12-17.0001.debugLog.log](https://github.com/user-attachments/files/18153966/2024-12-17.0001.debugLog.log)

**Comment by KIYI671** [comment]
> [2024-12-17.0001.debugLog.log](https://github.com/user-attachments/files/18153966/2024-12-17.0001.debugLog.log)
> 

绝了，有图片忘了上传传

**Comment by KIYI671** [comment]
> > [2024-12-17.0001.debugLog.log](https://github.com/user-attachments/files/18153966/2024-12-17.0001.debugLog.log)
> 
> 绝了，有图片忘了上传

好了，刚睡下又爬起来重新发布

**Comment by pevoku** [comment]
哈哈哈辛苦了

**Comment by pevoku** [comment]
今晚先睡吧 有问题也明天再发日志了 祝好梦

**Comment by pevoku** [comment]
恭喜 昨晚顺利挂了一晚上
