### ISSUE TITLE
Bug:一次完整运行后，会卡在领取奖励的页面

### ISSUE THREAD

**Issue by D1E4MF0I** [KIYI671/AhabAssistantLimbusCompany#61]
版本：v0.1.6.1
时间节点：2024-12-16 04:03:09
此后一直卡死在获取奖励的页面（镜牢领取奖励的页面
根据debugLog可知，此时程序还在想要继续获取主题包，获取ego事件图片，获取网络崩溃重试图片，疑似陷入循环且没有获取结束页面。
[logs.zip](https://github.com/user-attachments/files/18144080/logs.zip)

**Comment by KIYI671** [comment]
> 版本：v0.1.6.1
> 时间节点：2024-12-16 04:03:09
> 此后一直卡死在获取奖励的页面（镜牢领取奖励的页面
> 根据debugLog可知，此时程序还在想要继续获取主题包，获取ego事件图片，获取网络崩溃重试图片，疑似陷入循环且没有获取结束页面。
> [logs.zip](https://github.com/user-attachments/files/18144080/logs.zip)
> 

请问具体是卡在哪个页面？是那个能看各罪人输出的页面，还是后面的记分、展示敌人buff的页面？

**Comment by D1E4MF0I** [comment]
> 面

罪人输出的界面（有罪人大图像的那一页。
找不到图片，找到后我会尽快补充。

**Comment by KIYI671** [comment]
> > 面
> 
> 罪人输出的界面（有罪人大图像的那一页。
> 找不到图片，找到后我会尽快补充。

怪了，现在日志太多，手机看不过来，晚上再电脑仔细研究一下

**Comment by D1E4MF0I** [comment]
> > > 面
> > 
> > 
> > 罪人输出的界面（有罪人大图像的那一页。
> > 找不到图片，找到后我会尽快补充。
> 
> 怪了，现在日志太多，手机看不过来，晚上再电脑仔细研究一下

好的，麻烦大佬了(o゜▽゜)o☆

**Comment by D1E4MF0I** [comment]
> > 版本：v0.1.6.1
> > 时间节点：2024-12-16 04:03:09
> > 此后一直卡死在获取奖励的页面（镜牢领取奖励的页面
> > 根据debugLog可知，此时程序还在想要继续获取主题包，获取ego事件图片，获取网络崩溃重试图片，疑似陷入循环且没有获取结束页面。
> > [logs.zip](https://github.com/user-attachments/files/18144080/logs.zip)
> 
> 请问具体是卡在哪个页面？是那个能看各罪人输出的页面，还是后面的记分、展示敌人buff的页面？

![image](https://github.com/user-attachments/assets/332deb2a-c985-44aa-a55f-d9d28577f396)
这个页面，而且点了之后，直接就到了兑换页面。不过我刚刷的这次没卡，不知道问题原因。(´。＿。｀)

**Comment by KIYI671** [comment]
> > > 版本：v0.1.6.1
> > > 时间节点：2024-12-16 04:03:09
> > > 此后一直卡死在获取奖励的页面（镜牢领取奖励的页面
> > > 根据debugLog可知，此时程序还在想要继续获取主题包，获取ego事件图片，获取网络崩溃重试图片，疑似陷入循环且没有获取结束页面。
> > > [logs.zip](https://github.com/user-attachments/files/18144080/logs.zip)
> > 
> > 
> > 请问具体是卡在哪个页面？是那个能看各罪人输出的页面，还是后面的记分、展示敌人buff的页面？
> 
> ![image](https://private-user-images.githubusercontent.com/95405631/395965018-332deb2a-c985-44aa-a55f-d9d28577f396.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDg1OTEsIm5iZiI6MTczNDM0ODI5MSwicGF0aCI6Ii85NTQwNTYzMS8zOTU5NjUwMTgtMzMyZGViMmEtYzk4NS00NGFhLWE1NWYtZDlkMjg1NzdmMzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDExMjQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmOTBlYzRjYjQ5OWViNjQ5MmRjNjRkMjM5N2Y3YWYzMTI3NzE0YzE0NTA4NzIzN2Y4ZDVhNDMwNmJmMjNjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FaTCua3YBMYUHUj8eudvZoHDgQk9J-xsxyPqJvZQ3CM) 这个页面，而且点了之后，直接就到了兑换页面。不过我刚刷的这次没卡，不知道问题原因。(´。＿。｀)

分析了一下，大概是压榨战斗时间过狠的问题，下个版本会添加对应处理逻辑
