### ISSUE TITLE
Bug:进入战斗界面后，程序报错退出运行

### ISSUE THREAD

**Issue by D1E4MF0I** [KIYI671/AhabAssistantLimbusCompany#66]
具体报错内容如下：
2024-12-17 01:39:24 - debugLogger - "my_log\my_log.py:66" - my_log - ERROR - OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
打包log文件如下（包含log以及debugLog）
[logs.zip](https://github.com/user-attachments/files/18154671/logs.zip)

后续再次运行会再次进入一次战斗的运行逻辑，因此也丢失了问题情况的游戏截图，后续若有相同情况发生，将再次补充内容。

**Comment by D1E4MF0I** [comment]
虽然很不幸，但是立马复现成功了（大概
![F%Q_I31F0VB0@WVB{2WQWDL](https://github.com/user-attachments/assets/d7546539-bb7e-486a-a587-61e36924d9d1)
问题出现在加载页面，点击进入战斗后，在加载页面时出现此错误并使程序退出运行。
以下是最新log文件，已打包。
[logs.zip](https://github.com/user-attachments/files/18154794/logs.zip)

**Comment by KIYI671** [comment]
> 虽然很不幸，但是立马复现成功了（大概
> ![F%Q_I31F0VB0@WVB{2WQWDL](https://github.com/user-attachments/assets/d7546539-bb7e-486a-a587-61e36924d9d1)
> 问题出现在加载页面，点击进入战斗后，在加载页面时出现此错误并使程序退出运行。
> 以下是最新log文件，已打包。
> [logs.zip](https://github.com/user-attachments/files/18154794/logs.zip)
> 

你下载的是0.1.7版本，有一张图片忘记加入了，后面更新了0.1.7.1版本，这个版本应该没问题

**Comment by D1E4MF0I** [comment]
> > 虽然很不幸，但是立马复现成功了（大概
> > ![F%Q_I31F0VB0@WVB{2WQWDL](https://private-user-images.githubusercontent.com/95405631/396213307-d7546539-bb7e-486a-a587-61e36924d9d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDQxNTcsIm5iZiI6MTczNDQwMzg1NywicGF0aCI6Ii85NTQwNTYzMS8zOTYyMTMzMDctZDc1NDY1MzktYmI3ZS00ODZhLWE1ODctNjFlMzY5MjRkOWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDAyNTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YTFlOGViNGFhZDU5N2M3YjM2MTFlNGE0MDVkZmY4MWI2OWIzZGNhZTU1YWFmYzc2MmQ3ZDc3OGRhZTBjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lxPKtR8KxHHD3IWqITNdy13TqrAXYtKgY9Thyqt075s)
> > 问题出现在加载页面，点击进入战斗后，在加载页面时出现此错误并使程序退出运行。
> > 以下是最新log文件，已打包。
> > [logs.zip](https://github.com/user-attachments/files/18154794/logs.zip)
> 
> 你下载的是0.1.7版本，有一张图片忘记加入了，后面更新了0.1.7.1版本，这个版本应该没问题

好的，我再试试/_ \
