### ISSUE TITLE
Bug:任务运行过程中没有对游戏进程进行检测

### ISSUE THREAD

**Issue by NaNExist** [KIYI671/AhabAssistantLimbusCompany#71]
今天好像是因为手机上登陆顶号导致电脑端游戏关闭了
于是游戏没了但是aalc还在持之以恒的尝试检测
log就不贴了，单纯的全是检测不到
是不是可以考虑在任务执行的过程中增加对游戏是否在运行的检测
如果游戏似了就就终止任务？

不过这种情况算不算要考虑的也难说，可以不修

**Comment by KIYI671** [comment]
> 今天好像是因为手机上登陆顶号导致电脑端游戏关闭了
> 于是游戏没了但是aalc还在持之以恒的尝试检测
> log就不贴了，单纯的全是检测不到
> 是不是可以考虑在任务执行的过程中增加对游戏是否在运行的检测
> 如果游戏似了就就终止任务？
> 
> 不过这种情况算不算要考虑的也难说，可以不修

游戏似了是什么样的情况，没遇到过，也没想到过有这种问题( ﾟ∀。)
