### ISSUE TITLE
请问为什么用win键搜索“aalc.exe"打开会有错误

### ISSUE THREAD

**Issue by liaofuyi** [KIYI671/AhabAssistantLimbusCompany#76]
用其他方式打开的是正常的，但是搜索出来打开的：用不了（只会调整窗口）、报错
![屏幕截图 2024-12-22 210041](https://github.com/user-attachments/assets/94cf2dd8-846b-4915-b422-25170453dd72)
![屏幕截图 2024-12-22 210800](https://github.com/user-attachments/assets/4e1a9598-a10b-4c6e-ba3d-48f6644013d8)

**Comment by liaofuyi** [comment]
等我上传个日志文件，看大家都上传了

**Comment by liaofuyi** [comment]
[logs.zip](https://github.com/user-attachments/files/18221948/logs.zip)

**Comment by liaofuyi** [comment]
这太奇怪了，不过这发生在我搞了一些稀奇古怪的东西之后，之前是没有的

**Comment by KIYI671** [comment]
> 这太奇怪了，不过这发生在我搞了一些稀奇古怪的东西之后，之前是没有的

没遇到这种情况，从截图来看是读取不到图片导致的。
搜索到并启动的AALC，路径可能发生了变化，我看你搜索找到的路径在C:\My Program Files\AALC\AALC.exe，是否为你能正常启动时的路径？
目前怀疑搜索到的是另一个路径的另一份没解压完全的AALC，因为你发送的正常运行的日志中并无14：48这个时间点的记录。

**Comment by liaofuyi** [comment]
yes

**Comment by liaofuyi** [comment]
![Uploading 屏幕截图 2024-12-22 212714.png…]()

**Comment by liaofuyi** [comment]
![屏幕截图 2024-12-22 212714](https://github.com/user-attachments/assets/be128400-a5a3-46b3-9076-0dd24aba1dec)

**Comment by liaofuyi** [comment]
重装之后还是这个样子

**Comment by liaofuyi** [comment]
oh,no

**Comment by KIYI671** [comment]
> [logs.zip](https://github.com/user-attachments/files/18221948/logs.zip)
> 

恕我理解能力有限，无法get到你简短的语句中蕴含的无限含义
如果有什么其他发现反馈的话，请给予清晰、准确、详细的描述

**Comment by liaofuyi** [comment]
啊不好意思，就是文件的路径是对的，并且删除后在同一位置重新安装aalc后依然有相同的情况，请让我换一个路径试试，真不好意思，我得严肃一点，浪费作者大大的时间了(⊙﹏⊙)

**Comment by KIYI671** [comment]
> 啊不好意思，就是文件的路径是对的，并且删除后在同一位置重新安装aalc后依然有相同的情况，请让我换一个路径试试，真不好意思，我得严肃一点，浪费作者大大的时间了(⊙﹏⊙)

你可以尝试全局搜索2024-12-22.0001.debugLog.log这个文件名，因为如果有另一个路径的话，应该也会生成另一份日志文件
如果使用windows自带的搜索过慢的话，可以尝试使用everything这个软件
