### ISSUE TITLE
无法打开应用程序

### ISSUE THREAD

**Issue by TheRicers** [KIYI671/AhabAssistantLimbusCompany#8]
以下内容由谷歌翻译翻译：

我遇到了一个问题，我无法打开该应用程序，如果我尝试打开该应用程序，它会弹出一条错误消息：

Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "my_gui.py", line 636, in mygui
  File "my_gui.py", line 575, in read_last_setting
TypeError: 'NoneType' object is not subscriptable
![NVIDIA_Share_I0XYPbJv7a](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/122712149/b512f29a-d732-4a2a-bc41-d7d59f94394b)

**Comment by KIYI671** [comment]
> 以下内容由谷歌翻译翻译：
> 
> 我遇到了一个问题，我无法打开该应用程序，如果我尝试打开该应用程序，它会弹出一条错误消息：
> 
> Traceback (most recent call last):
>   File "main.py", line 18, in <module>
>   File "my_gui.py", line 636, in mygui
>   File "my_gui.py", line 575, in read_last_setting
> TypeError: 'NoneType' object is not subscriptable
> ![NVIDIA_Share_I0XYPbJv7a](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/122712149/b512f29a-d732-4a2a-bc41-d7d59f94394b)
> 
> 

根据你提供的截图，之所以出现这个情况，可能是因为读取配置文件的步骤出现了问题。请使用文本编辑器查看程序文件夹下的“confirm.yaml”文件，请确保文件的内容应如图所示，是使用键值对形式（左边文本，中间：，右边数字或文本）保存数字或文本，文件中最前方为#的注释行可以忽略![IMG_20240618_080905.jpg](https://github.com/KIYI671/AhabAssistantLimbusCompany/assets/26021800/b8d64376-9da1-4815-9741-ad7d0f62aa41)

**Comment by TheRicers** [comment]
谢谢作者，现在可以正常工作了。由于某种原因，config.yaml 的内容被完全删除了，但它又可以正常工作了，顺便说一句，在镜像地牢中，如果罪人的生命值已满，当应用程序试图在休息站/商店中治疗时，它似乎会出错，只能一遍又一遍地按跳过。你也可以为应用程序做一个简单的翻译来支持英语吗？谢谢你的辛勤工作，兄弟

**Comment by KIYI671** [comment]
> 谢谢作者，现在可以正常工作了。由于某种原因，config.yaml 的内容被完全删除了，但它又可以正常工作了，顺便说一句，在镜像地牢中，如果罪人的生命值已满，当应用程序试图在休息站/商店中治疗时，它似乎会出错，只能一遍又一遍地按跳过。你也可以为应用程序做一个简单的翻译来支持英语吗？谢谢你的辛勤工作，兄弟

谢谢你对我的程序的支持，兄弟。
这个问题之前在V0.0.2已经解决了，它会最多尝试五次点击跳过，这是为了防止电脑配置不足导致的卡顿现象，如果在五次跳过后仍旧在治疗选择页面，它会自动退出。
关于翻译的问题，可能后续会在readme放出程序页面各个功能的文字对照。我经过这次项目，发现了我没有系统学习过编程的局限性，最近在重新学习编程的基础入门课程，导致我的空闲时间被占据了。我设想如果添加语言切换功能，将通过按键来对整个程序的语言进行切换，但是目前没有时间和精力以及技术来达成我想要效果，所以很抱歉只能先搁置对于这个功能的实现了。

**Comment by TheRicers** [comment]
谢谢兄弟的辛勤工作，祝你学业顺利

**Comment by KIYI671** [comment]
你好，我已经在readme中添加了简单的脚本程序各个页面的说明，你可以前往查看。如果你觉得有什么地方说明得不够清楚的，请提出，我将在后续进行修改。
