### ISSUE TITLE
BUG:主题卡包黑名单及队伍成员死亡检测可能不生效

### ISSUE THREAD

**Issue by Cure2004** [KIYI671/AhabAssistantLimbusCompany#81]
![screenshot](https://github.com/user-attachments/assets/a9fd63b3-b407-4e9c-9d16-359fe1519a79)
卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面

**Comment by KIYI671** [comment]
> ![screenshot](https://github.com/user-attachments/assets/a9fd63b3-b407-4e9c-9d16-359fe1519a79)
> 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面

黑名单实现的原理是通过OCR(文字识别)功能识别卡包上的文字，判断是否存在黑名单卡包的关键词，但是因为OCR有时候会因为图片光影、遮挡等情况出现误差，导致只能尽力避免，还是有部分可能误选。
个人测试时未出现这个情况，你可以为黑名单增加关键词，比如"murder"，或者"express"，来提高对此卡包的识别率

**Comment by KIYI671** [comment]
> ![screenshot](https://github.com/user-attachments/assets/a9fd63b3-b407-4e9c-9d16-359fe1519a79)
> 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面

还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个

**Comment by NaNExist** [comment]
> > ![screenshot](https://github.com/user-attachments/assets/a9fd63b3-b407-4e9c-9d16-359fe1519a79)
> > 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面
> 
> 还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个

感觉可以学隔壁给黑名单加上权重，就算都在黑名单也会选择权重低好打一点点的主题

**Comment by KIYI671** [comment]
> > > ![screenshot](https://github.com/user-attachments/assets/a9fd63b3-b407-4e9c-9d16-359fe1519a79)
> > > 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面
> > 
> > 还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个
> 
> 感觉可以学隔壁给黑名单加上权重，就算都在黑名单也会选择权重低好打一点点的主题

哪个隔壁？参考一下( ﾟ∀。)
实际上因为默认选择加主题包的那个初始星光，我没遇到过这种情况

**Comment by NaNExist** [comment]
> > > > ![screenshot](https://private-user-images.githubusercontent.com/192770363/398527463-a9fd63b3-b407-4e9c-9d16-359fe1519a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjI1NzYsIm5iZiI6MTczNTI2MjI3NiwicGF0aCI6Ii8xOTI3NzAzNjMvMzk4NTI3NDYzLWE5ZmQ2M2IzLWI0MDctNGU5Yy05ZDE2LTM1OWZlMTUxOWE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMTE3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTM4ZDVjMDEyNDk2NzgzNTBkNzRlNWVlMzczOTJhNTM0NDZiY2I2YzkyOGY5NTE4ZWUzMmNmZWFjODhjM2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UpLRPs9Vz-MLDBSu4_cPvDm9n0fZHws7hxKWk3XltPM)
> > > > 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面
> > > 
> > > 
> > > 还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个
> > 
> > 
> > 感觉可以学隔壁给黑名单加上权重，就算都在黑名单也会选择权重低好打一点点的主题
> 
> 哪个隔壁？参考一下( ﾟ∀。) 实际上因为默认选择加主题包的那个初始星光，我没遇到过这种情况

就是MAA打方舟的肉鸽时候，选择干员是根据配置文件里面的权重来选的

**Comment by KIYI671** [comment]
> > > > > ![screenshot](https://private-user-images.githubusercontent.com/192770363/398527463-a9fd63b3-b407-4e9c-9d16-359fe1519a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjI1NzYsIm5iZiI6MTczNTI2MjI3NiwicGF0aCI6Ii8xOTI3NzAzNjMvMzk4NTI3NDYzLWE5ZmQ2M2IzLWI0MDctNGU5Yy05ZDE2LTM1OWZlMTUxOWE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMTE3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTM4ZDVjMDEyNDk2NzgzNTBkNzRlNWVlMzczOTJhNTM0NDZiY2I2YzkyOGY5NTE4ZWUzMmNmZWFjODhjM2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UpLRPs9Vz-MLDBSu4_cPvDm9n0fZHws7hxKWk3XltPM)
> > > > > 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面
> > > > 
> > > > 
> > > > 还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个
> > > 
> > > 
> > > 感觉可以学隔壁给黑名单加上权重，就算都在黑名单也会选择权重低好打一点点的主题
> > 
> > 哪个隔壁？参考一下( ﾟ∀。) 实际上因为默认选择加主题包的那个初始星光，我没遇到过这种情况
> 
> 就是MAA打方舟的肉鸽时候，选择干员是根据配置文件里面的权重来选的

话说打人皮书会不会几个回合后切状态，上次有一次好像自动切了，但是没印象是不是烧伤队

**Comment by KIYI671** [comment]
> > > > > ![screenshot](https://private-user-images.githubusercontent.com/192770363/398527463-a9fd63b3-b407-4e9c-9d16-359fe1519a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjI1NzYsIm5iZiI6MTczNTI2MjI3NiwicGF0aCI6Ii8xOTI3NzAzNjMvMzk4NTI3NDYzLWE5ZmQ2M2IzLWI0MDctNGU5Yy05ZDE2LTM1OWZlMTUxOWE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMTE3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTM4ZDVjMDEyNDk2NzgzNTBkNzRlNWVlMzczOTJhNTM0NDZiY2I2YzkyOGY5NTE4ZWUzMmNmZWFjODhjM2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UpLRPs9Vz-MLDBSu4_cPvDm9n0fZHws7hxKWk3XltPM)
> > > > > 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面
> > > > 
> > > > 
> > > > 还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个
> > > 
> > > 
> > > 感觉可以学隔壁给黑名单加上权重，就算都在黑名单也会选择权重低好打一点点的主题
> > 
> > 哪个隔壁？参考一下( ﾟ∀。) 实际上因为默认选择加主题包的那个初始星光，我没遇到过这种情况
> 
> 就是MAA打方舟的肉鸽时候，选择干员是根据配置文件里面的权重来选的

感觉似乎可以设置所有卡包权重，取消黑名单机制，改为白名单机制( ﾟ∀。)

**Comment by NaNExist** [comment]
> > > > > > ![screenshot](https://private-user-images.githubusercontent.com/192770363/398527463-a9fd63b3-b407-4e9c-9d16-359fe1519a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjI1NzYsIm5iZiI6MTczNTI2MjI3NiwicGF0aCI6Ii8xOTI3NzAzNjMvMzk4NTI3NDYzLWE5ZmQ2M2IzLWI0MDctNGU5Yy05ZDE2LTM1OWZlMTUxOWE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMTE3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTM4ZDVjMDEyNDk2NzgzNTBkNzRlNWVlMzczOTJhNTM0NDZiY2I2YzkyOGY5NTE4ZWUzMmNmZWFjODhjM2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UpLRPs9Vz-MLDBSu4_cPvDm9n0fZHws7hxKWk3XltPM)
> > > > > > 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面
> > > > > 
> > > > > 
> > > > > 还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个
> > > > 
> > > > 
> > > > 感觉可以学隔壁给黑名单加上权重，就算都在黑名单也会选择权重低好打一点点的主题
> > > 
> > > 
> > > 哪个隔壁？参考一下( ﾟ∀。) 实际上因为默认选择加主题包的那个初始星光，我没遇到过这种情况
> > 
> > 
> > 就是MAA打方舟的肉鸽时候，选择干员是根据配置文件里面的权重来选的
> 
> 感觉似乎可以设置所有卡包权重，取消黑名单机制，改为白名单机制( ﾟ∀。) 不过白名单要查所有卡包，会不会拖慢时间啊 不过白名单可以自选容易打的，比如鸡煲，利弊难定

查卡包时间占比感觉已经很小了，慢一点也无所谓吧( ﾟ∀。)

**Comment by KIYI671** [comment]
> > > > > > > ![screenshot](https://private-user-images.githubusercontent.com/192770363/398527463-a9fd63b3-b407-4e9c-9d16-359fe1519a79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjI1NzYsIm5iZiI6MTczNTI2MjI3NiwicGF0aCI6Ii8xOTI3NzAzNjMvMzk4NTI3NDYzLWE5ZmQ2M2IzLWI0MDctNGU5Yy05ZDE2LTM1OWZlMTUxOWE3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QwMTE3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTM4ZDVjMDEyNDk2NzgzNTBkNzRlNWVlMzczOTJhNTM0NDZiY2I2YzkyOGY5NTE4ZWUzMmNmZWFjODhjM2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UpLRPs9Vz-MLDBSu4_cPvDm9n0fZHws7hxKWk3XltPM)
> > > > > > > 卡包黑名单里有warp列车杀人案，但今天挂机刷的时候突然发现自动选了，然后打不过，队伍的人全死光，以至卡在最终关的选人界面
> > > > > > 
> > > > > > 
> > > > > > 还有一种极端情况，如果刷新了几次，几个卡包都在黑名单中，那么就会随机选择一个
> > > > > 
> > > > > 
> > > > > 感觉可以学隔壁给黑名单加上权重，就算都在黑名单也会选择权重低好打一点点的主题
> > > > 
> > > > 
> > > > 哪个隔壁？参考一下( ﾟ∀。) 实际上因为默认选择加主题包的那个初始星光，我没遇到过这种情况
> > > 
> > > 
> > > 就是MAA打方舟的肉鸽时候，选择干员是根据配置文件里面的权重来选的
> > 
> > 感觉似乎可以设置所有卡包权重，取消黑名单机制，改为白名单机制( ﾟ∀。) 不过白名单要查所有卡包，会不会拖慢时间啊 不过白名单可以自选容易打的，比如鸡煲，利弊难定
> 
> 查卡包时间占比感觉已经很小了，慢一点也无所谓吧( ﾟ∀。)

那就加入待办事项，估计还要搞个GUI出来比较好配置
